### ISSUE TITLE
Add question regarding information on BMSY/B0

### ISSUE THREAD

**Issue by dtdougherty** [shcaba/FishPath-updates#1]
This question needs to be created including: question wording, answer options, which options it impacts and what minimum criteria level is required.  Should be linked to DB-SRA

**Comment by shcaba** [comment]
This needs to be added as a critrion to DCAC and DB-SRA. 
Wording and answers can be just like the FMSY/M question.

It can used is SSS, but doesn't have to be.  You have to have either steepness OR BMSY/B0 + FMSY/M.

**Comment by bsnouffer** [comment]
New question text (copying from the FMSY/M question): 
"Do you have an estimate of BMSY/B0 (the ratio of the biomass level that produces MSY, to virgin biomass)?"

Answers (also from FSMY/m):
0: No
1: Borrowed or empirically derived
2: Measured, but with high uncertainty (e.g. low sample size, outdated data, sampling from a small area of a bigger spatial scale, or unable to differentiate gender-specific values)
3: Measured, with low to moderate uncertainty (e.g., good sample size, up to date, covers the spatial range of the species)

Question to be put in order right after the FMSY/M question.

Mark as criterion for options:
 - DCAC
 - DB-SRA
 
Need to determine if possible to list a criteria as A OR (B AND C), might be a way to use nested satisfied by "OR" questions, but not sure how that would be handled in the code. Right now SSS has steepness listed as a criteria and nothing for FMSY/M. For now suggesting to leave as is until this can be tested. Probably worth adding a new issue noting this situation.

Question for review: Are there any tools that can help find this information that can be included in the question description?

**Comment by shcaba** [comment]
From Thorson et al. 2012 Table 2


Species | SBMSY/SB0 | CV
-- | -- | --
All | 0.404 | 0.136
Taxonomic | groupings
Pleuronectiformes | 0.395 | 0.122
Gadiformes | 0.439 | 0.125
Perciformes | 0.353 | 0.12
Clupeiformes | 0.261 | 0.105
Scorpaeniformes | 0.463 | 0.126
Other | 0.405 | 0.127

These are the first and fourth columns of the table. This simple table could go right into the question.

**Comment by shcaba** [comment]
We should also consider making a note in the steepness criterion output for Stock Synthesis that, in lieu of steepness, it can use SBMSY/SB0 and FMSY/M.

Everything else looks good and is ready to be linked in FishPath.

**Comment by bsnouffer** [comment]
Added question. Still need to add the table as tables cannot be entered into the text editor. Instead a screenshot of the table will be added, however there is currently an issue where images are not working in the questionnaire (#261). Will add the table once this is fixed. Also creating new issue to address the criteria logic A OR (B AND C)
