### ISSUE TITLE
Ability to set temporary access to FishPath or password protect different versions

### ISSUE THREAD

**Issue by serenalomonico** [shcaba/FishPath-updates#102]
For “light touch” trainings, is there a way to set up a temporary access limit (such as – this link and your access will expire in 2 weeks)?  This can currently be done manually by Chad, he says this is easier than developing an entire admin interface for accounts.

Password protection in FishPath version 1.0. Each new version could have a different password.

**Comment by dtdougherty** [comment]
for launch, we likely need to send a note to all with access and then approve all that requested access but were not granted. In the meantime, if we want to remove people or notify people they only have 2 weeks, this is possible, but needs to be communicated well.

**Comment by bsnouffer** [comment]
Closing. The Tool has been soft launched and anyone can register and access it. Instructions are being provided to those who were waiting approval on how they can access the Tool.
