### ISSUE TITLE
Ability to easily return to continue editing an in-progress session

### ISSUE THREAD

**Issue by serenalomonico** [shcaba/FishPath-updates#106]
Need the ability to find link for editing fishery that was started if email is lost. We need process for when people lose support email, or if we want to override for some reason.

It is hard to go back in and get into your saved session.  First, there are two options (continue existing, or other) when you follow link from email and it is not clear which does which.  Then If I want to get back in, it starts me half way through survey and I have to hit next many times to get to results.  Sometimes it takes me straight to results, not consistent. They should always be able to go to some “home page” and then choose to edit questions, see results, etc.

**Comment by serenalomonico** [comment]
Serena: This has been partly resolved in that the user is now directed to the “home page” and then can choose to edit questions, see results, etc. Could be more streamlined when entering a section of the in-progress questionnaire (numbers displayed on home screen for question progress don't match what the user sees once back into the section).

**Comment by underbluewaters** [comment]
Closing this as 99% has been resolved and question numbers are referenced in other tickets.
