### ISSUE TITLE
Add question regarding sex-changing individuals

### ISSUE THREAD

**Issue by serenalomonico** [shcaba/FishPath-updates#108]
We need a question for sex-changing individuals. If a species changes sex, you want to implement a minimum size limit to ensure the individuals have a chance to change sex and reproduce. Also need to know if the species is sperm-limited or not to define the right size limit.

**Comment by serenalomonico** [comment]
This is related to issue #92

**Comment by serenalomonico** [comment]
Add question about if species can be sexed at all (this has been added to FishPath), OR if the fishery takes only one sex (e.g. because this is the only gender whose size is greater than the minimum size limit).  If cannot be sexed, or if take only one gender, then any sex-based regulations cannot be applied. 

Note that if only one gender is taken, fishery dependent information gives no information on the other gender (QDAF workshop Brisbane).

**Comment by NatalieDowling** [comment]
Added following questions:
- Does the species change sex (i.e. exhibits protogyny - begins life as a female and changes to a male) or protandry (begins life as a male and changes to a female)? (invokes green for size limit; yellow on sex specific Management Measures)
- Can the sex of the species be determined at all? (invokes caveats against sex-based management measures)
- Does the fishery take only fish of a single sex? (this invokes caveats against both Data Collection and Management Measures sections)

QUESTION ORDER will need to be addressed.

**Comment by dtdougherty** [comment]
I adjusted question order. 
I think that the new question "Can the sex of the species be determined at all" could be combined with the existing question "Can the sex of the species be determined without causing the animal’s death?". Both invoke the same set of caveats against sex-based management measures. The existing question also has a yellow caveat against using electronic monitoring:cameras for biological info, saying that it is unlikely it would capture information that would be used to sex animals. This could apply to both.

**Comment by serenalomonico** [comment]
Agree with @dtdougherty 's suggestion. A suggestion from Mexico technical workshop was to add a short description that this refers to either the species as either dead or live if the chosen question wording to keep is "Can the sex of the species be determined at all? (invokes caveats against sex-based management measures)"

**Comment by NatalieDowling** [comment]
I have changed the original question wording to "Can the sex of the species be determined (with or without causing the animal's death)?" and deleted the "...at all?" question. I have also cleaned up the electronic monitoring caveats so that these apply across all data categories, and also to shore-based cameras and VMS.
