### ISSUE TITLE
Consider adding a description/clarifier of data quality for questions about time series of data

### ISSUE THREAD

**Issue by serenalomonico** [shcaba/FishPath-updates#109]
As an upfront instruction, need to qualify to user that there is the inherent assumption that if you state that you have a certain time series of data, that this is assumed to be of reliable quality – that is, the user feels as though the data can be used in an empirical or model-based stock assessment.

**Comment by serenalomonico** [comment]
Put this in both the relevant question descriptions AND the introduction to the Assessment portion of the questionnaire. Need to qualify that users need to consider the assessment questions based on their best available data.

**Comment by dtdougherty** [comment]
can be merged with issue #168

**Comment by shcaba** [comment]
Getting addressed in #168
