### ISSUE TITLE
In questionnaire, make the section (Data Coll, Assmt, Mmgt Measures) more obvious to the user

### ISSUE THREAD

**Issue by serenalomonico** [shcaba/FishPath-updates#111]
The “Data Collection”, “Assessment”, “Decision Rules” headings should be in larger font in the questionnaire. This will help users keep the context in mind when answering questions. Or, find a way to feature the questionnaire section better (ie something explicit like "You are in the Data Collection section of the FishPath questionnaire").

**Comment by dtdougherty** [comment]
I think this is okay? The section is displayed in bold at the top of the questionnaire screen.
