### ISSUE TITLE
Turn caveats into sentences

### ISSUE THREAD

**Issue by serenalomonico** [shcaba/FishPath-updates#116]
In general, many caveats could include more text/description. Caveats that say “YES” or “Caution” should be turned into a sentence. Add information on how to overcome if possible.

**Comment by serenalomonico** [comment]
Also, aspects of the caveats (e.g. spatial-temporal representativeness, changes in gear type affecting selectivity) needed to be carefully explained. Need accompanying links to references per Fisheries Science 101.

**Comment by serenalomonico** [comment]
Caveats that start with “given there exist conditions…” should be reworded.

**Comment by serenalomonico** [comment]
Specifically, the wording of decision rule (management measure) caveats, e.g. “strongly consider” for red. All need to be checked and revised as appropriate. Possible task for Josh and Natalie.

**Comment by dtdougherty** [comment]
This is a major undertaking. Jeremy attempted, but then realized that turning all "Yes" responses into a sentence was not easy, as the context of each yes is different and expansion on that requires some tailoring per entry or by category, question, etc.

**Comment by serenalomonico** [comment]
Edit specific caveat text: For limited entry, need to change the latent effort caveat text from "no" to "consider augmenting with other rules". (-Serena/Jono on Dec. 11 reviewing penshell results).

**Comment by bsnouffer** [comment]
First pass of rewording all caveats with less than 10 characters is completed and inputted into FishPath. Natalie is now going to take a first pass at reviewing all of the rest of the caveats in the management measures section. Thanks Natalie!

Closing this. Any future suggestions for specific caveat updates should be put into its own issue.
