### ISSUE TITLE
Update caveat colors and icons

### ISSUE THREAD

**Issue by shcaba** [shcaba/FishPath-updates#122]
We should change the color of one of these. Having both be gray is confusing.
The gray caveats should also show up next to green, not orange.

**Comment by dtdougherty** [comment]
There should not be gray caveats. We can address this in two ways: 1. Have Chad export a list of gray caveats sot that we can edit those in the admin section, this should be a quick fix, just requires thoughtful assignment of colors; and 2) have Chad disable gray (and purple) as color options in the caveat interface.

**Comment by dtdougherty** [comment]
consider changing static caveats to a color (blue, purple..?)

**Comment by dtdougherty** [comment]
Clean up the questions that have grey caveats and disable grey caveats.
Change static caveats to aqua-marine.
Turn squares/circles into all circles.

**Comment by dtdougherty** [comment]
All grey caveats have been removed, this will now be turned into a software issue to address the following:
1. On results screen, change color of static caveats (grey box) to aqua-marine
2. On results screen, have turn boxes (now green and grey) into circles like the others. Now all would be circles with aqua-marine for static caveats, red/orange/yellow for cautionary caveats, green for positive caveats. No grey would appear.
3. Disable color choices of grey or purple for caveats.

**Comment by bsnouffer** [comment]
One wrinkle here is that currently, static caveats can be assigned colors other than grey. Many of the electronic monitoring options currently have this. Interestingly, no matter the color, static caveats show up in the results row as grey. 

Results row - EM: shore based cameras:
![image](https://user-images.githubusercontent.com/11687620/52808821-af176980-3043-11e9-9056-2552b7f92619.png)

Detailed view of static caveat for share based camera:
![image](https://user-images.githubusercontent.com/11687620/52808789-97d87c00-3043-11e9-99e5-cb8c7b25d02a.png)

**Comment by dtdougherty** [comment]
These should all be grey (aqua-marine in future). And we need to change this so that admin users cannot change the color of this.

**Comment by bsnouffer** [comment]
Static caveats weren't being exported with the rest of the caveats so I
added a static caveat tab in the google sheets page.

https://docs.google.com/spreadsheets/d/1oBvUSCDObKob2hGOTqizjLmzx7vK4S3sdRAPvMa8kxs/edit?usp=sharing

**Comment by dtdougherty** [comment]
Thanks! I assume if we change the color across the board to aqua-marine, we
can just change them all at once and not worry about any that are yellow or
other right now.

**Comment by underbluewaters** [comment]
Completed in mcclintock-lab/FishPath@de5d57831c39fa0e4026d002cb06b761f77258de

**Comment by underbluewaters** [comment]
<img width="1153" alt="Screen Shot 2019-07-19 at 2 22 59 PM" src="https://user-images.githubusercontent.com/511063/61566375-c9a9a080-aa30-11e9-9965-9f2c4b7a4ebd.png">

<img width="822" alt="Screen Shot 2019-07-19 at 2 23 37 PM" src="https://user-images.githubusercontent.com/511063/61566385-d75f2600-aa30-11e9-920f-ee6720db8090.png">
