### ISSUE TITLE
Add the ability to consider combinations of data collection options

### ISSUE THREAD

**Issue by serenalomonico** [shcaba/FishPath-updates#125]
Example: May need to think about approaches in combination – qv Canadian BC Groundfish fishery use of video footage – 10% (affordable) audits to validate logbooks, which are the primary source of fishery-dependent monitoring. Separate monitoring options may not be the whole story – BC manages low-cost monitoring with logbooks, with validity ensured by auditing 10% of video footage. Much more affordable than 100% video monitoring. May need to consider combinations of monitoring options.

**Comment by serenalomonico** [comment]
Related: Have ability to identify 1-2 primary monitoring types. Consider what information is not being collected by these, and identify secondary options that could be used to augment or validate the primary options. Additional column in output? (QDAF workshop)

**Comment by dtdougherty** [comment]
We now have process to identify front runner options. Maybe in guidance, we need to explicitly state that one may not be adequate and options may complement each other. This general philosophy is something that should be considered across the board. 
1. Say this up front in workshops: updated in guidance doc.
2. Address this in the results guidance as a guiding principle up front: "Don’t be compelled to find only one option. Options can be used in combination to best reach fishery objectives."
3. It may also be helpful to provide a few examples of how fisheries used combinations of options.

**Comment by serenalomonico** [comment]
This info was added to results review process; captured in other GitHub issues.
