### ISSUE TITLE
Consider incorporating/addressing "Evolutionary tree" of Assessment methods

### ISSUE THREAD

**Issue by serenalomonico** [shcaba/FishPath-updates#126]
"Evolutionary tree” of assessment methods – orange static caveat if a method has been superseded or is generally considered obsolete. Could also consider a static caveat around whether the assessment method is recent/has been superceded/isn’t used much now.

**Comment by bsnouffer** [comment]
Complexity sorting is being adding and there is guidance given to generally use more complex assessment methods if available. Closing for now. Can revisit this if determined to be needed later on.
