### ISSUE TITLE
Consider adding a "green static caveat" to recommend exploratory/risk analyses 

### ISSUE THREAD

**Issue by serenalomonico** [shcaba/FishPath-updates#128]
Exploratory analyses, risk analyses – green-light static caveat recommending these to understand data and fishery, prior to undertaking more formal stock assessments.

**Comment by bsnouffer** [comment]
The new column, assessment 'tier', explicitly denotes options that are pre-assessment risk analyses. This is good guidance for facilitators to keep in mind when planning a workshop. For individual users, this advice is called out in the user guide under the assessment 'tier' description. Closing as this change should get at highlighting risk analyses without the need for a static caveat.
