### ISSUE TITLE
Add new question: Are effort units meaningful? (QDAF workshop)

### ISSUE THREAD

**Issue by serenalomonico** [shcaba/FishPath-updates#133]

**Comment by shcaba** [comment]
To examine this issue, is this saying whether the level of resolution for effort data makes sense? For instance, days for hours. Some effort measures are going to be rubbish and they don't detail the catch and effort enough to get at abundance. We should make that clear. 
If I am on the right track, the question could be "Is effort measured at a level meaningful to interpret CPUE as a measure of abundance? If the effort metric is too course (e.g., per week), this may not be adequate to track abundance using catch. 

The caveat would be if the answer is no, then any method using CPUE may have questionable trends.
Would we also want a green if the answer is yes? Probably so.

**Comment by jonowilson** [comment]
this makes perfect sense to me

**Comment by bsnouffer** [comment]
Addressed on a call with Natalie and Jason. Decided to capture this in the effort and CPUE time series questions (257 and 263). Updated the description to effort time series:
"This question refers to the recorded history of fishing effort, reported in units (e.g., hours, trips) that are consistent through the time series. 
The resolution of the effort units is assumed to capture important attributes or changes in the effort - that is, the effort time series should be a meaningful signal of the fishing activity.
In this context, higher resolution effort units (e.g., hours vs days) are typically desired, as courser units may obscure attributes or changes." 
and updated the 0 answer to "absent, or not meaningful"

for 263 updated description:
"This refers to data collected without the initial intent of measuring abundance. A common example is catch-per-unit-effort (CPUE) information based on data collected from a fishery, then standardized to represent abundance.
Note that, in the context of CPUE, the resolution of the effort units is assumed to capture important attributes or changes in the effort - that is, effort should be a meaningful signal of the fishing activity."
and 0 answer to "0: Absent, or 1 year of relative abundance index, or effort not meaningful (if using CPUE) "
