### ISSUE TITLE
Resolve Logic behind Length Data in Question 227

### ISSUE THREAD

**Issue by serenalomonico** [shcaba/FishPath-updates#14]
227: What time series exists of length composition data?
This question refers to data from either fishery-dependent or fishery-independent sampling.

Note from Conil workshop:  In certain fisheries, there are 2 length bins such as “small” and “big” (bocinegro). You cannot do a catch-curve analysis with this type of resolution. This option is "red" because of the amount of length data. The question does not get at the **quality** of length data – it asks about the **time series** or amount of data – edit the question. Natalie’s point is that catch curves require more. 

Please note there is a separate question 239: "What time series exists of percentile length data (mean, median, x percentile)?"

**Comment by bsnouffer** [comment]
This was added to the question description at some point: 

> The resolution of length categories or bins needs to be fine enough so that cohorts are discernible. Two or three size categories such as "big", "medium" and "small" is insufficient for the purposes of this question.

Closing as this seems to address the concern.
