### ISSUE TITLE
Add new question: does life history (i.e. generation time) impact on the ability to meaningfully assess the stock (if the available time series of data is less than the generation time)? (Canada)

### ISSUE THREAD

**Issue by serenalomonico** [shcaba/FishPath-updates#142]

**Comment by shcaba** [comment]
This is related to question #143, so comments should be combined (or one of these closed). While this is an issue, I think it is a difficult one to provide simple guidance, and it will take a bit of time to get it right. But it does need to be addressed at some point.

**Comment by bsnouffer** [comment]
Moved to #143 as Jason suggests. Closing.
