### ISSUE TITLE
Add caveat that multispecies fisheries have certain monitoring options that do lend themselves to capturing all rather than key species (TBL workshop Brisbane)

### ISSUE THREAD

**Issue by serenalomonico** [shcaba/FishPath-updates#146]

**Comment by serenalomonico** [comment]
Consider in Data Collection section revamp. ND: This is a new caveat that is required – some data collection options lend themselves to capturing all species in a multispecies fishery, and we should green-caveat those that do, and perhaps yellow-caveat those that do not.

**Comment by dtdougherty** [comment]
We added caveats against the multi-species fishery question that gives cautions or greens around data collection and representation in a multi-species fishery
