### ISSUE TITLE
Check how Question 1548 crosses 2 questionnaire sections

### ISSUE THREAD

**Issue by serenalomonico** [shcaba/FishPath-updates#15]
1548: Rank the current or potential monetary investment for a data collection program for this species/species group. 

FishPath Team: The “data collection” term in question 1548 (current or potential monetary investment) should possibly be “management measures”. Needs Natalie review, as it spans both Data Collection and Management Measures. Question should address both or be split into two.

**Comment by dtdougherty** [comment]
1. update the wording to match #545
2. Add a description, that says funding can come from many (e.g. 2144)

**Comment by dtdougherty** [comment]
Update this to match question #545 in terms of criteria (only low invoke) and cautionary caveats.

**Comment by dtdougherty** [comment]
Done, double check expert knowledge with group
