### ISSUE TITLE
Hyperlink to open in new window not working

### ISSUE THREAD

**Issue by dtdougherty** [shcaba/FishPath-updates#151]
In the option description, we have added hyperlinks to some of the text. When creating the hyperlink, we select the "open in a new window" option, but that does not seem to be working. It opens in the same window.

**Comment by dtdougherty** [comment]
This is not working in the questionnaire descriptions either.

**Comment by underbluewaters** [comment]
Is this still happening? I tried it in both the reference section and the results for Option description and it behaves as it should. All links should open in a new window, regardless of the setting in the wysiwyg editor.
This wasn't the behavior for Question descriptions, and that has now been fixed.

**Comment by dtdougherty** [comment]
I think this was just in the question descriptions, so if that is fixed, we should be good.

**Comment by underbluewaters** [comment]
Great. I've got a fix for questions but it's not deployed yet.
