### ISSUE TITLE
User account: reset password not working

### ISSUE THREAD

**Issue by dtdougherty** [shcaba/FishPath-updates#154]

**Comment by underbluewaters** [comment]
The user accounts system that we use assumes that users will have confirmed their email address before having access to the password reset functionality. This email confirmation step was disabled for simplicity's sake but we may have to re-enable it to fix this functionality. Alternatively, we could wait until the tool is open-access. It seemed to work fine when accounts were automatically enabled.
The last alternative, which would work regardless of account activation settings, would be to create a lambda script that runs on account creation and automatically confirms the user's email address and enables password reset. That task is what is estimated.

**Comment by underbluewaters** [comment]
Ah, I mentioned making an estimate but I can't add labels due to my account permissions. @dtdougherty can you give me write access to this repo?

**Comment by dtdougherty** [comment]
Sure, I don't know how to do that though. I thought we all had write access.

**Comment by underbluewaters** [comment]
It should be under the Settings tab in the Teams and Collaborators section. It might be that only @shcaba has access to those settings.
