### ISSUE TITLE
Add ability to send email notifications to users: 3rd party 

### ISSUE THREAD

**Issue by dtdougherty** [shcaba/FishPath-updates#155]

**Comment by dtdougherty** [comment]
This idea is to have the ability to send software updates/changes to FishPath users after launch. Alternatively, we could add a pop-up or something to notify users when they log in of major changes since their last use.

**Comment by dtdougherty** [comment]
Same as issue #129

**Comment by serenalomonico** [comment]
In the future with Coaches Network, consider service such as MailChimp to contact registered folks, with live integration to FishPath account emails. In meantime, Chad may be able to just download a list of emails.

**Comment by bsnouffer** [comment]
Integration with mailchimp was added earlier this year. Emails of current users at the time were exported and added to the list and all new users get their email added to the newsletter list when checking the box at sign up. They are able to unsubscribe at any time and maintain their account.
