### ISSUE TITLE
Double check Assessing Escapement Through Samples of Catch

### ISSUE THREAD

**Issue by serenalomonico** [shcaba/FishPath-updates#157]
JW: The “assessing escapement through samples of catch…” should not say “to ensure 30% have spawned’, it should just say till “X percent” or minimum percent . 30% is just arbitrary. 

Title: Assessing escapement through samples of catch to ensure 30% have spawned
[Output Category: Catch or Fishing Rate, Input Category: Life History-Based Reference Points]

Description:
This assessment option provides a method for using estimated biomass levels, fishing rates, and proportional egg escapement levels to guide management action. In the fishery management plan for market squid in California, a biological reference point (BRP) of 30% egg escapement was adopted as a temporary measure for managing fished stocks until biomass could be estimated. To identify an appropriate BRP for this temporary measure, Dorval et al. (2013) extended earlier egg escapement models. These earlier models calculated fishing mortality rate (F) based on catch fecundity, which is the number of eggs remaining in harvested females' reproductive tracts (Macewicz et al., 2004; Maxwell et al. 2005). Dorval et al. extended this model by also calculating an estimate of total abundance for California market squid, along with estimates of F and proportional egg escapement (calculated as estimated eggs-per-recruit relative to estimated eggs-per-recruit without fishing). As this example demonstrates, estimated biomass levels, fishing rates, and proportional egg escapement levels can be used to guide management action, including setting F such that proportional egg escapement is greater than 30%.

**Comment by bsnouffer** [comment]
Title was previously updated to "Assessing escapement through samples of catch".

I updated the last sentence to also help show 30% is arbitrary. It now reads:  "... including setting F such that proportional egg escapement is greater than _a minimum threshold_."
