### ISSUE TITLE
Update contacts that contain 'For more information contact XXX'

### ISSUE THREAD

**Issue by bsnouffer** [shcaba/FishPath-updates#170]
The following list "For more information contact XXX" as the contact information:

In Data Collection:
Port/landing site monitoring - Category: To inform stock status

In Management Measures:
Daily trip limits, with or without TAC - Category: Catch Limits
Seasonal closures - Category: Temporal Management
Minimum legal size - Category: Size Limits

**Comment by dtdougherty** [comment]
Removed these references.
