### ISSUE TITLE
Results Narrowing: Management Measures Instructions Text

### ISSUE THREAD

**Issue by serenalomonico** [shcaba/FishPath-updates#171]
Check these 2 text lines in instructions- not relevant for MM section? (Jono/Serena).
- We have hidden all options where criteria were not met.
- Unhide any hidden options worth reinstating.

FULL TEXT: 
**Instructions**
First, we want to quickly narrow down the list and remove options that are clearly not on the table, using the “hide” (greyed out) and “un-hide” functions. We have hidden all options where criteria were not met.
Unhide any hidden options worth reinstating.
Hide any options after reviewing the bottom of the list with the most warnings (given current default sort).
Hide any other options that are inconsistent with legislation or on-the-ground conditions.

**Comment by bsnouffer** [comment]
This was updated in Feb 2019 (along with an update to most/all the results review text) to the following:

> First, we want to quickly narrow down the list and remove options that are clearly not on the table, using the “hide” (greyed out) and “un-hide” functions.
Use the default sort and hide any options after reviewing the top of the list with the most warnings
Sort by category and hide categories that are not relevant or available to the fishery.
Hide any other options that are inconsistent with legislation or on-the-ground conditions.
After review of influential answers and related caveats, hide options where caveats flagged cannot be corrected for.

Closing.
