### ISSUE TITLE
Double check in MM section: Latent effort shouldn't matter with catch limit

### ISSUE THREAD

**Issue by serenalomonico** [shcaba/FishPath-updates#172]
Serena/Jono reviewing Penshell fishery results on 12/11/18 and noted this.

**Comment by bsnouffer** [comment]
@serenalomonico, just following up on this. I see there is a caveat against each catch limit option in MM for the question "Is there latent effort in the fishery?" 

A yellow caveat reads for 2 catch limit options (set by time, set by area) 

> NO unless this is a secondary control rule - effectiveness may be compromised by activation of latent effort

An orange caveat for the other 6 catch limit options reads

> NO - effectiveness may be compromised by activation of latent effort
 
Am I correct in thinking that you and Jono are suggesting these should not be caveats? Given that if latent effort activates, the catch limit is still in effect and doesn't change based on effort.

However, there are two options that can set catch limits by fisher (Daily trip limits, with or without TAC and Gear-unit limits, with or without TAC). These would still be affected by latent effort if used without a TAC.

**Comment by bsnouffer** [comment]
Natalie is doing a full review of management measures caveats. These comments will be taken into consideration during the review.

**Comment by NatalieDowling** [comment]
Thank you - this is a good pickup. For the 6 catch limit options that would be unaffected by the activation of latent effort, I have replaced the caveat with 

"Green: Yes: Catch limits are a direct control on fishing mortality that are unaffected by the activation of latent effort."

For Daily trip limits, with or without TAC, and Gear-unit limits, with or without TAC, I have replaced the caveat with

"Orange: Yes : The effectiveness of daily trip limits (gear unit limits) in the absence of a TAC may be compromised by the activation of latent effort."

**Comment by bsnouffer** [comment]
Looks good. Added to FishPath. Communication for this will be covered in a broad MM caveats update note.
