### ISSUE TITLE
Add short description to question #338

### ISSUE THREAD

**Issue by serenalomonico** [shcaba/FishPath-updates#173]
During Callo de Hacha run through, participants thought it would be useful to specify or provide clarity on the time period in question: 

"Has the selectivity pattern changed over time?" (currently no description). 
https://fishpath.org/admin/questions/338 

(from Serena/Jono Penshell Dec. 2018)

**Comment by NatalieDowling** [comment]
Suggest adding "....over the time series for which data (that would be used within an assessment) are available)?"

Suggest adding in description: Time series data may not be commensurate if the selectivity has changed.

Needs group approval.

**Comment by shcaba** [comment]
I think there are two parts here. There is over the time period of the data as Natalie has pointed out, which will directly determine how the data are interpreted, but there should also be some thought as to any changes outside the data window in the case that time period is when the majority of catches occurred, thus a better overall representative of the removal data.

**Comment by bsnouffer** [comment]
Assigning back to @NatalieDowling to address the additional consideration Jason brought up in review. Natatie, feel free to directly assign this back to Jason when you are done with it.

**Comment by NatalieDowling** [comment]
I have added the following text to the Description:

"Time series data may not be commensurate if the selectivity has changed. 
In answering this question, consider the entire history of removals, including
- changes over the time series for which data (that would be used within an assessment) are available
- whether there may have been changes outside of the timeframe over which data are available (e.g., in the case that this non-data time period is when the majority of catches occurred)."

**Comment by shcaba** [comment]
Looks good to me.

**Comment by bsnouffer** [comment]
Looks like Natalie added this to FishPath yesterday. Moving to communication column.
