### ISSUE TITLE
Check which methods carry an assumption of constant recruitment 

### ISSUE THREAD

**Issue by serenalomonico** [shcaba/FishPath-updates#179]
"Check which methods carry an assumption of constant recruitment" was an old team note. Checked with Natalie and asked if this was flagged in the last round of assessment revisions, ND reply was "There is a question about whether users have an understanding of recruitment variability, and whether the concept of an equilibrium biomass is meaningful. But we don’t have this constant recruitment assumption explicitly addressed. Perhaps need to check this with Jason."

**Comment by shcaba** [comment]
So this would be a static caveat, and effect the following methods:
YPR
XSSS
XDBSRA
SSS
DBSRA
DCAC
CMSY
OCOM 
SSCOM
LBSPR
LBRP
LBB
All the "Analysis of changes" options
Analysis of size relative to size at maturity
Catch curve analysis
Mean length
B-K life history
SPRMER
CC-SRA
intrinsic rebound potential
matrix models
demographic FMSY
COM-SIR

**Comment by bsnouffer** [comment]
Proposed and review done over email with Jason:

Hi Jason,

I am working on a static caveat to address the constant recruitment assumption. For this, do you think something simple will suffice or should it contain more details? For example, it could read along the lines of "This method assumes constant recruitment." or "This method assumes constant recruitment and does not account for recruitment variability."

Or should it contain more detail about what can be done to address this assumption such as "This method assumes constant recruitment. This can increase the uncertainty of the analysis. Use methods such as sensitivity analyses to explore this uncertainty."

At first I was leaning towards having a longer description, but thinking further upon it, handling assumptions is a general thing that needs to be done no matter the method and we probably don't need to make a suggestion for every assumption listed, unless there is something very specific to that assumption that can be done. Handling assumptions is probably better handled through discussion in the workshops, than notes in the caveats.

Brian

Hi Brian,

I like the simplest example you gave. In this case, there really isn't much more to say; and as you mention, if you start adding recommendations to confront the assumption, that opens up the need to do it everywhere.

-Jason

**Comment by bsnouffer** [comment]
I will input the static caveat: "**This method assumes constant recruitment.**" for the methods Jason listed above.

**Comment by bsnouffer** [comment]
Inputted. Closing.

**Comment by bsnouffer** [comment]
Further refined based on peer review comment. See updated caveats here: 
https://docs.google.com/spreadsheets/d/1JZEs-_b-7prZVS1QdzD3VBAlqpue1YF7x2bE6ekw8F8/edit?usp=sharing
