### ISSUE TITLE
Note on Data Collection Options and static caveats

### ISSUE THREAD

**Issue by serenalomonico** [shcaba/FishPath-updates#180]
Old team note: "Add a static attribute that could have existing monitoring that is not aimed at gathering information on target species, but may be more around environment (e.g. observers for TEPs) or legislative requirement as condition of permit, but largely used for compliance (logbooks)."

ND: "I think this involves reviewing all the monitoring options and adding static caveats where relevant. This is really just meant to serve as food for thought, that while you may have existing programs, their emphasis may not have been on data collection to inform an assessment."

**Comment by dtdougherty** [comment]
Done. Added caveats around certain options.
