### ISSUE TITLE
Add a question about higher-level requirements / green caveat those options that are required

### ISSUE THREAD

**Issue by serenalomonico** [shcaba/FishPath-updates#181]
Address higher level requirements, such as around HCRs, or identify broader requirements that equate to fixed management measures (such as rulings on gear restrictions). I’m not sure that this translates across to developing nations. Suggest we add a question about whether there are higher-level gear, spatial, or other requirements (e.g. manage by TACs), and, according to responses, flag those measures that are required by law or policy as green caveats. - ND

**Comment by bsnouffer** [comment]
Seems close enough to #68 that I am closing as duplicate as they should be reviewed at the same time (legislative and any other higher requirements). I will copy the content over so it doesn't get lost.
