### ISSUE TITLE
Check terminology "Catch Records" in Data Collection section

### ISSUE THREAD

**Issue by serenalomonico** [shcaba/FishPath-updates#182]
In the Data Collection section, I dislike the use of “catch records” to replaces “catch disposal records or sales dockets”. It’s too easily confused with logbook records. Perhaps we need to make this explicit (e.g. “Catch records, by third party” or something).

**Comment by bsnouffer** [comment]
I had this same thought when reviewing this option. Here is a link to recommendations I am proposing to clarify this option. To me, the description currently is focusing on options that seek to address IUU fishing through traceability. So I propose changing the name to "Catch and Traceabiltiy Records" which doesn't play favorites to the different names being used for full traceability systems (CDS, CDT, etc) and I think can still encompass methods such as fish tickets. I also highlight a couple possible changes to the criteria. 

https://docs.google.com/document/d/1Jv3GO8EwDRg4YjhIx5OR_jr8KXAGwqLcjWGHjd_zHyc/edit

**Comment by dtdougherty** [comment]
update wording from Brian
