### ISSUE TITLE
Canceling doesn't reset answer in answer pop up

### ISSUE THREAD

**Issue by bsnouffer** [shcaba/FishPath-updates#184]
Steps to reporduce:
1) Go to answers page
2) Click on a question
3) Change the answer
4) Click cancel
5) Click to reopen the same question

The answer you changed to before will still be highlighted, however that answer was not saved and the results were not updated (correctly since it was canceled). This behavior might be confusing to users as they may think that answer was saved or they might be confused about what the original answer was. Refreshing the page will return the pop up to display the correct answer when opened.

**Comment by underbluewaters** [comment]
Fixed but not yet deployed
