### ISSUE TITLE
Counting in questionnaire is off

### ISSUE THREAD

**Issue by dtdougherty** [shcaba/FishPath-updates#186]
After the first section has been completed in the questionnaire, the subsequent sections have an error when counting the questions ("question # of # remaining"). The numbering bounces around.

**Comment by underbluewaters** [comment]
Do you know what section was started first?

**Comment by dtdougherty** [comment]
We did Management Measures and then Assessments. I have seen this problem
before, so I don't think it is unique to this order.

**Comment by dtdougherty** [comment]
Jono noted this worked well in Peru workshop. I will test again and confirm.

**Comment by underbluewaters** [comment]
I've improved the consistency of these counts. Not sure that will get rid of all the numbering bugs but at least I knocked out two sources of problems. The summary page wasn't considering satisfiedBy-type questions and the progress bar in the Questionnaire wasn't considering what was already answered in another section in some cases.
