### ISSUE TITLE
Remove Preview step in results review

### ISSUE THREAD

**Issue by dtdougherty** [shcaba/FishPath-updates#188]
The "Preview screen" in the results review process is a bit confusing when working with a workshop (Dawn and Jono's opinion).  For now we propose:

1. Removing this step from the preview process 
and/or
2. Replacing it with a diagram or similar that illustrates the major categories of options to orient users to what the longer list contains.

**Comment by underbluewaters** [comment]
Just confirming, we will keep *Review Full Results* step and just remove *Preview*?

**Comment by dtdougherty** [comment]
Yes, we would just remove the "preview" step.

**Comment by dtdougherty** [comment]
Brian and Serena, I am still a fan of this. I would even suggest removing both the "preview" screen and "view full results" screen, since that is what you do when you first enter results. Brian, can you update this or is this a Chad fix. If you guys agree (and Brian can do), let's tag Jason and Natalie for review and approval.

**Comment by serenalomonico** [comment]
Agree @dtdougherty to remove both "Preview" and "View Full Results".

**Comment by bsnouffer** [comment]
@dtdougherty I can make these changes on the software side.

**Comment by dtdougherty** [comment]
Hi all, tagging everyone for agreement. I propose removing both the "preview" screen and "view full results" screen when you are in the results narrowing process. This seems awkward, since they have seen the full list in the regular view. This results narrowing should jump into the process. Thoughts?

**Comment by shcaba** [comment]
I agree with Dawn.

**Comment by NatalieDowling** [comment]
I totally agree, too. Thanks!

**Comment by jonowilson** [comment]
let's do it!

**Comment by bsnouffer** [comment]
I will add this to my list to get done.

**Comment by bsnouffer** [comment]
Removed both "preview" and "view full results" steps. mcclintock-lab/FishPath#60
