### ISSUE TITLE
Define "immediate concern" in Question 1200

### ISSUE THREAD

**Issue by serenalomonico** [shcaba/FishPath-updates#19]
1200: Is there immediate concern, among any stakeholder group, regarding stock status?

FishPath Team: Clarify the wording because the “immediate concern” phrase is not very clear (of course there is always concern). Add a description that says "Immediate concern" refers to... or simply remove the phrase and replace with another.

**Comment by NatalieDowling** [comment]
I have changed "immediate" to "strong" and have added in the Description,
"Here, we intend "strong" to mean concern that equates to the perceived need for urgent intervention or change."
Requires approval.

**Comment by bsnouffer** [comment]
@dtdougherty did you review this? If so can you add a comment stating that you did. Natalie had made this change before the process, but was still asking for someone else to review it so thought we would just add it to the review stage of the board.

**Comment by dtdougherty** [comment]
This looks okay to me and is complete in FP.
