### ISSUE TITLE
Results don't automatically update when changing an answer in the influential answers section

### ISSUE THREAD

**Issue by bsnouffer** [shcaba/FishPath-updates#190]
When you change and save an answer in the influential answers section, the change is not seen in the results section. You must refresh the page before the change is seen. This could lead to confusion for users if they are expecting the change to be automatically reflected in the results.

**Comment by underbluewaters** [comment]
This is some sort of shouldComponentUpdate oversight somewhere. Should be relatively easy to fix.

**Comment by bsnouffer** [comment]
This creates even more confusion than first realized. The results dont update as described above, however the answer will change in the caveat details. This makes it seem that the new answer triggered the old caveat. For example, the old answer to "does the fishery take only fish of a single sex?" was "Yes". This triggered a red caveat for market surveys (biol info). An answer of no triggers no caveat for that option. I changed the answer from "yes" to "no" in the influential answer section. The results section does not update and the red caveat is still shown for the option. However the answer listed in the caveat detail shows the new answer "no" under the red caveat caused by the old answer ("yes"). This will make users incorrectly think that the new answer caused the same caveat, unless (or until) they refresh the page. 

Caveat detail for market survey (biol info) after changing the answer from "yes" to "no" without refreshing the page:
![image](https://user-images.githubusercontent.com/11687620/79780820-5dc2d400-82f1-11ea-90b6-e5a645a8d809.png)

**Comment by bsnouffer** [comment]
This also occurs when updating answers from the bookmarked questions section.

**Comment by bsnouffer** [comment]
Fixed in mcclintock-lab/FishPath#75
