### ISSUE TITLE
Check caveats and options invoked by Question 1318 

### ISSUE THREAD

**Issue by serenalomonico** [shcaba/FishPath-updates#20]
1318: “Is the fishery multispecies, either in terms of target or bycatch species?” 

FishPath Team: There was large group discussion around the question's intent during the Conil workshop. Intent is to be proactive and answer “yes” conservatively. For example, if you are catching bocinegro, it’s also possible that you get voraz - in these terms, the fishery is multispecies. 
To resolve, check if this question invoke catch limits and other options? There are a lot of caveats on this question, not sure of the action (if any) needed other than a thorough check.

**Comment by serenalomonico** [comment]
This question 1318 also needs to be better differentiated from question 1457 (see other issue devoted to this)

**Comment by bsnouffer** [comment]
Closing. I think this concern should be considered as part of the broader review of multispecies questions listed in #21. Copying the comment over so it doesn't get lost.
