### ISSUE TITLE
Need to make the default order in the Assessment section reflect the rigor of the assessment category.

### ISSUE THREAD

**Issue by shcaba** [shcaba/FishPath-updates#201]
The current default order is alphabetical, which causes confusion.

**Comment by dtdougherty** [comment]
Yes, we have discussed before, we would need to provide this ordered listing to Chad. Is this something that Jason can propose?

**Comment by bsnouffer** [comment]
related to #94

**Comment by dtdougherty** [comment]
We have sent ordering to Chad to update in next sprint

**Comment by underbluewaters** [comment]
Can somebody please post the assessment options order to this ticket? I don't see it anywhere in my emails.

**Comment by bsnouffer** [comment]
Assessment 'tiers' were added to the assessment options. These reflect the complexity/rigor of the option. The default sorting now places available mid and high tier assessment options above data-poor and pre-assessment available options. Eliminated options are listed at the bottom. Users can also now sort by the assessment 'tier'. Sorting by option name is still available. It could be removed if desired, but there might be a rare use case where a user is trying to find a specific option and going through an alpha sorted list is easiest to read through. 

Closing.
