### ISSUE TITLE
Re-word and fix typo in Retention option #2

### ISSUE THREAD

**Issue by shcaba** [shcaba/FishPath-updates#210]
Hide any options after reviewing the TOP of the list with the most warnings (given current default sort).
This wording also could do for an edit.

**Comment by bsnouffer** [comment]
This step also has a typo "2. ...and hide **_any any_** options after reviewing..."

**Comment by bsnouffer** [comment]
Fixed the typos. Currently in discussions for a broader overhaul of this process and there are a number of other issues that track that, so closing this now. mcclintock-lab/FishPath#60
