### ISSUE TITLE
Glossary for jargon terms

### ISSUE THREAD

**Issue by shcaba** [shcaba/FishPath-updates#213]
Having a pop-up window that contains a glossary of some of the jargon or harder to understand terms would be nice. We could add a live link to the word in each question that takes you to the pop-up.

**Comment by bsnouffer** [comment]
A glossary has been published in the user guide and is live now. The next step will be to add hyperlinks in the questions for any of the terms.

https://fishpath.github.io/FishPath-Tool-User-Guide/glossary.html

**Comment by bsnouffer** [comment]
I added the ability to use hyperlinks (and other text formatting) in the question itself and have gone through and added hyperlinks where the terms appear in the questions. Closing this issue. If a definition should be updated or new term added, open a new issue to document that.
