### ISSUE TITLE
Add YPR analyses

### ISSUE THREAD

**Issue by dtdougherty** [shcaba/FishPath-updates#215]
In Peru workshop, Ana suggested that we do YPR analyses for this species, but that are not listed as assessment options now.

**Comment by shcaba** [comment]
This is on the long list of methods to add Brian is working on.
It is important to remember that this methods only gives reference points. We should probably describe how it can be coupled with catch curves or mean length methods to actually inform overfishing status.

**Comment by bsnouffer** [comment]
Closing as its covered in #42
