### ISSUE TITLE
Review caveats for "Do stock assessments suggest that overfishing is probable, for any species harvested?"

### ISSUE THREAD

**Issue by dtdougherty** [shcaba/FishPath-updates#225]
The "unassessed" answer option was added to this question, and caveats need to be posted against this if needed. For example, if they mark unassessed, we may want to warn against catch limits or support NTZs or size limits.

**Comment by NatalieDowling** [comment]
I have made an attempt at completing this. Requires approval.

**Comment by shcaba** [comment]
Natalie and I went through it together, made one change, and it is now ready to move on!
