### ISSUE TITLE
Allow users to edit fishery name and details (particularly for copy fishery)

### ISSUE THREAD

**Issue by bsnouffer** [shcaba/FishPath-updates#229]
Noticed then when trying out the copy fishery button. I might be missing it, but I didn't see an easy way to change a fishery name. Currently the copy fishery automatically gives the new fishery the same name. This will be confusing and won't allow users to update the name and now fishery details if they are copying to use for a different metier or hypothetical situation. Consider allowing to edit these details.

Also, might be worth thinking of popping up the new fishery details screen when copying (populated with the current info). This will also allow people to cancel the copy if they accidentally click the copy button. As now it creates the copy directly on the click and with no way to delete yet, this could be frustrating to users.  At a minimum, I think creating a confirm copy pop up would be smart.

**Comment by dtdougherty** [comment]
Agree with Brian's suggestion, especially with prompting the fishery detail screen. When doing a retrospective analysis, it will be important to track which one is the actual fishery we should be using. Is it the original, and all others flagged as copy? We need to think through this.

**Comment by underbluewaters** [comment]
It should be pretty easy to implement a prompt to update the response name. We could also append "(Copy)" automatically, but I didn't want to do that without name editing since it would be easy to end up with (Copy) (Copy) (Copy) etc.

**Comment by dtdougherty** [comment]
Got it, yes it would be good to allow editing, but also append Copy, which
they can remove if needed.

**Comment by dtdougherty** [comment]
Also, this feature is really nice when you have a link to someone else's fishery, because it automatically creates a copy in your own folder, and the naming is less of an issue. Perhaps if we allow them to edit the name, we can automatically default the type of session to "test" instead of "stakeholder session", which they could change if needed.

**Comment by dtdougherty** [comment]
Note, there should also be a place to review and edit fishery information from that initial screen. once you complete that intake screen, there is no way to go back in and edit or view.
