### ISSUE TITLE
In answer change pop up, caveats without text appearing

### ISSUE THREAD

**Issue by bsnouffer** [shcaba/FishPath-updates#231]
Options that have caveats that once had text saved, but since been deleted appear in the change answer pop up as impacted. Below is for the question "Does the stock move beyond the boundaries of where the fishing or sampling takes place (i.e., is the stock transboundary)?", but I have seen it at least one other question, but have not done a thorough accounting to find everywhere it occurs. 

![image](https://user-images.githubusercontent.com/11687620/53218256-49f9e000-3610-11e9-856d-ae2d30e4324e.png)

Technically, this appears to be happening because deleted caveats are not fully removed from the database. They still are listed in the domain logic in the question list. The text is cleared, but the caveat remains. For example (question (417) -> domainLogic -> caveats):

![image](https://user-images.githubusercontent.com/11687620/53218451-018ef200-3611-11e9-9473-ad1155543789.png)

This appears to be a separate issue from #230 as these are regular caveats and are not being shown in the results list.

**Comment by underbluewaters** [comment]
Good catch! Seems like there should be a step in the qdd saving process that weeds these out from existing questions, as well as an update to QuestionDomainLogicSettings to make sure it generates the appropriate data in this case.

**Comment by bsnouffer** [comment]
This appears to have been caused by the same underlying issue that was fixed in #278. Closing as this is no longer occurring for the workflow described with the fix to 278 complete.
