### ISSUE TITLE
Cannot see all sections in choosing results with small screen

### ISSUE THREAD

**Issue by bsnouffer** [shcaba/FishPath-updates#237]
If the screen size or window is small then the "view results" buttons might not show up on the pop up when selecting a fishery to look at results. Scrolling only scrolls the background, not the pop up so there is no way to access. You can still access the button by hitting tab a number of times to change the focus to the button, but this is not obvious. I also saw this occur previously in Indonesia on a participants computer, but cannot find an issue here. Fortunately we figured out the tabbing work around. 

![image](https://user-images.githubusercontent.com/11687620/54729818-cbc32780-4b42-11e9-9946-80c67a7ea965.png)

**Comment by underbluewaters** [comment]
Do you know what kind of device this was? Even on a 600px tall browser window this should work. Easy enough to fix with a css rule.

<img width="897" alt="Screen Shot 2019-05-28 at 10 35 36 AM" src="https://user-images.githubusercontent.com/511063/58499161-625c2800-8134-11e9-8c33-0f990ec940f5.png">

**Comment by bsnouffer** [comment]
Unfortunately I don't remember what computer she was using.

**Comment by bsnouffer** [comment]
Added a scrollbar when needed. Closing.
