### ISSUE TITLE
Add criteria count icon to influential answers

### ISSUE THREAD

**Issue by bsnouffer** [shcaba/FishPath-updates#238]
The icon showing the number of options affected by a question in the influential answers section does not display anything for failed criteria.

Each of the questions without an icon and count next to them shown here affect only criteria:
![image](https://user-images.githubusercontent.com/11687620/55044555-040dae80-4ff8-11e9-805b-f7280f9d7283.png)

**Comment by dtdougherty** [comment]
counts are not showing and the sort might be off. Revisit sort order.

**Comment by underbluewaters** [comment]
Counts are included in consideration of sort now:
https://github.com/mcclintock-lab/FishPath/commit/356840fe2868091bb10a11e614783d6ab1a37507

Need to add an icon to represent them.

**Comment by bsnouffer** [comment]
Previously always showed only caveat counts in influential answers section, now shows counts for caveats and/or criteria if they are affected. Also, previously it would change the counts based on which options were being displayed (ie if not showing hidden options, then counts changed). However, the scores to calculate which answers were influential did not change based on what options were shown/filtered. In general there are some UI inconsistencies concerning the icons still within the influential and full answers sections. I will write up a new issue to document my notes on it for a larger review in the future.

![image](https://user-images.githubusercontent.com/11687620/74076573-9ed36980-49cd-11ea-9707-31a7fc389483.png)

Fixed in mcclintock-lab/FishPath#63
