### ISSUE TITLE
New Fishery information screen sizing

### ISSUE THREAD

**Issue by dtdougherty** [shcaba/FishPath-updates#239]
When starting a new fishery, there is a new user input screen to capture basic information on that fishery. Depending on the screen size of the user, all of the options may or may not appear on the window. Users can scroll to the bottom to see all options, but it is not automatically apparent that there are more options. We may want to have the "submit" button not show until they have scrolled to the bottom, or somehow make it obvious that there are more options to review.

**Comment by underbluewaters** [comment]
Right now this is not scrollable but I can make it so and force the display of a scroll bar indicator. Note that this should only happen on extremely small screens.

**Comment by dtdougherty** [comment]
Brian- is this something you could fix. I only see some of the options, so it looks like there are onle 3 or so options depending on how I adjust my screen size.

**Comment by bsnouffer** [comment]
I can take a look at it.

**Comment by bsnouffer** [comment]
Updated to have a scroll bar when needed. Also reworded the context question to "In which of these 5 contexts is the FishPath tool being used for this fishery?" in order to highlight that there are more options if the screen has cut off some of the radio buttons.

Done in mcclintock-lab/FishPath#69
