### ISSUE TITLE
3 Similar Questions: Check caveats and possibly merge

### ISSUE THREAD

**Issue by serenalomonico** [shcaba/FishPath-updates#241]
https://fishpath.org/admin/questions/417
Does the stock move beyond the boundaries of where the fishing or sampling takes place (i.e., is the stock transboundary)?
When answering, do not include the boundaries of no-take zones unless no-take zones comprise a large portion of the fishable area.
 
https://fishpath.org/admin/questions/691
Does a substantial proportion of the fished population cross management boundaries?
For example, the fished stock may be highly migratory, crossing jurisdictional boundaries and migrating through the managed area.
 
https://fishpath.org/admin/questions/2150
Do the jurisdictional management boundaries match with the fish stock boundaries?
Select 'No' if significant numbers of fish are moving across boundaries, such that a monitoring program will not sample from the entire extent of the stock.

**Comment by NatalieDowling** [comment]
The first two questions (417 and 691) should absolutely be merged. 

The first (417) invokes caveats only in the Assessment section.
The second (691) invokes caveats only in the Data Collection section.

I suggest "Does a substantive proportion of the fished population move beyond the boundaries of where the fishing or sampling takes place?" and then include the descriptions from both questions.

I think the third question is subtly different and can likely be left as is.

**Comment by bsnouffer** [comment]
691 now has caveats in Management Measures as well. But I don't think that changes Natalie's point that 691 and 417 should be merged. I agree with her proposed new question text and description. I will make this change in FishPath next week unless someone suggests a reason why they should stay separate. @shcaba @jonowilson @serenalomonico @dtdougherty @NatalieDowling

**Comment by NatalieDowling** [comment]
Thank you, Brain, and I am MORE than happy for you to make this change.

**Comment by NatalieDowling** [comment]
*Brian. 
Freudian slip.

**Comment by bsnouffer** [comment]
Merged 417 into 691 and updated the text based on above. 417 is now deleted.
