### ISSUE TITLE
"previous" link in questionnaire not working

### ISSUE THREAD

**Issue by dtdougherty** [shcaba/FishPath-updates#242]
We were working in the data collection section, around question 9?, and I tried to hit previous to revisit the previous question and it would send me out of the questionnaire screen back to the start. It worked later in the questionnaire, so I don't know what this particular issue was.

**Comment by underbluewaters** [comment]
It could have been because the questionnaire was in "finish mode". I'm going to close this issue as a duplicate of #244.
