### ISSUE TITLE
Create "cheat-sheet" export

### ISSUE THREAD

**Issue by dtdougherty** [shcaba/FishPath-updates#252]
I think this is flagged somewhere, and being worked on by Brian. It would be nice to have a cheat-sheet export, similar to the original spreadsheets, where facilitators can get a quick glance of what questions are impacting. This is helpful in talking through questions and understanding answer impacts.

**Comment by serenalomonico** [comment]
Related to Issue #63

**Comment by bsnouffer** [comment]
Added in mcclintock-lab/FishPath#55
