### ISSUE TITLE
Need to update wording of Question ID: 1697?

### ISSUE THREAD

**Issue by dtdougherty** [shcaba/FishPath-updates#256]
What is the level to which the broader community regards formal management as a “good thing,” in terms of compliance with and support for management measures?

Description:“Community” refers to the broader society and/or associated coastal communities.

Ana comments:  unclear what this question informs. Does it refer to the fishing community?

She may have not seen description. May need to review for better wording or connection to impacts in results.

**Comment by bsnouffer** [comment]
Updated the question to remove "community" from the question and "directly state society or associated coastal communities" instead.

Question now reads: What is the level to which broader society or associated coastal communities, support formal management (via a harvest strategy), in terms of upholding compliance with management measures?

Also updated the description to: 
Examples of such support include
- willingness to report instances of non-compliance
- refusing to support black market sales
- buyers refusing sub-legal (e.g. undersize, or caught out of season) product

Answer "moderate" if there is a mixed level of support (e.g. some community members uphold compliance, whilst others do not).

Natalie and I completed this while reviewing other peer review comments about this question. It has been updated in the Tool. Could still have the question editor contractor review this.
