### ISSUE TITLE
Remove RapFish

### ISSUE THREAD

**Issue by dtdougherty** [shcaba/FishPath-updates#258]
Comment from Ana:
I wonder if we need to keep RapFish among the assessment options.

**Comment by jonowilson** [comment]
I agree. and would also reconsider the need for CARE, ERAEF, PSA

**Comment by shcaba** [comment]
We've considered the recommendation to do the risk analysis types approaches to help prioritize a multi-species FishPath approach. So I think those methods have their place, but I see how they normally will come before doing a more management-linked data-limited method.

**Comment by NatalieDowling** [comment]
I agree with Jason that these methods have their place. They are clearly classified as risk assessments. We have many harvest strategies here in AUS that, in very data-limited cases, are centred around risk assessments.

**Comment by NatalieDowling** [comment]
If we seriously want to reconsider including the risk assessments, then we should have a discussion about what the assessment section of FishPath is for, and more generally, our criteria for what is and is not included. I prefer an inclusive approach. We can always put warnings on the risk assessments, if desired.

**Comment by bsnouffer** [comment]
Assessment 'tiers' have now been added to the tool (see #271). Risk assessments (and life history methods) are even more clearly defined now. Risk assessments (and life history methods) are now also auto hidden in results if there is a mid or high assessment 'tier' option available. Given the discussion above and what has come out of the large amounts of planning and discussion from designing the assessment 'tier' for the tool, these options should still be included.

Closing this. If there is disagreement or other counter arguments come up in the future, please reopen or write a new issue.
