### ISSUE TITLE
Post image not working in question interface

### ISSUE THREAD

**Issue by dtdougherty** [shcaba/FishPath-updates#261]
Email correspondence:
Hi Dawn,
It looks like this has been broken since I deployed the new server system early this year. In fact, it looks like I completely forgot to implement it...
It will be a couple weeks before I can get this added. For now, if you can put those on a public image hosting system (Dropbox, etc) you can use the url form to add an image to FishPath.
-Chad

On Wed, Apr 3, 2019 at 2:33 PM Dawn Dougherty <dtdoug@gmail.com> wrote:

    Hi Chad,

    Last summer we imported all of the questions again, because we had made so many changes to the wording. In that process, we removed the three graphics attached from some of the question descriptions, so that the import process would work. I am trying to add them back in, but when I upload them, they show in the questionnaire as "undefined". I know this functionality was working fine earlier, and thought I would check first to make sure I am using the correct file type, etc. If you have any tips let me know, or we many need to look into this further at some point.

    Thanks,
    Dawn

**Comment by bsnouffer** [comment]
This issue has been fixed and tested. Pictures can be added to the questionnaire.
