### ISSUE TITLE
Add caveats for question "Are data that are to be used within an assessment collected using a different gear than used by fishers?"

### ISSUE THREAD

**Issue by NatalieDowling** [shcaba/FishPath-updates#266]
This question only invokes a single caveat, against the escapement assessment. This should invoke warnings against any assessment that can use fishery independent data. Also, this issue should maybe be included as a static caveat against the fishery independent data collection options.

**Comment by shcaba** [comment]
Natalie is totally right on this.  Need to look through the methods, but many of the length-based methods could invoke a caveat that says "Data may create biased results in this method. Reconsider using the data or determine a modification of the data to approximate the selectivity of the fishery".

**Comment by shcaba** [comment]
This will apply to all currently included size-based methods. The caveat I mentioned before could be added to these methods.

**Comment by bsnouffer** [comment]
4 methods currently have an orange caveat "Sampling must occur using same gear as in the fishery"

- Assessing escapement through samples of catch
- LB-SPR
- LIME
- LBB

I suggest updating this text to that suggested by Jason above. 

Also consider adding the rest of the options that use length comps/percentile as a criteria:

- SCAA
- Analysis of length/size-specific catch-rate indicators for fish sampled inside and outside of marine protected areas (MPAs) or established no-take zones/reserves, and per-recruit
- Catch curve analysis
- Analysis of sustainability indicators based on length-based reference points (LBRP)
- RAPFISH
- CC-SRA
- Mean length mortality estimators
- qR Method (weight percentile)



**Regarding adding a static caveat to the independent survey options:** 
All ind. survey options have the static caveat: "provides no fishery dependent information"

Half (listed below) have the additional text: "selectivity may be different to that of fishing fleet"

- By researchers, performed regularly - Cat: To inform model-based stock assessment
- By researchers, performed regularly - Cat: Biological Information
- By researchers, performed irregularly - Cat: To inform model-based stock assessment
- By fishers, performed irregularly - Cat: Biological information
 
I propose adding the additional text about selectivity to the other options (listed below):

- By researchers, performed irregularly - Cat: Biological information
- By fishers, performed irregularly - Cat: To inform model-based stock assessment
- By fishers, performed regularly - Cat: To inform model-based stock assessment
- By fishers, performed regularly - Cat: Biological information

**Comment by bsnouffer** [comment]
Sending to @shcaba to review.

Can you let me know if there are any of those options listed that should not receive either the orange caveat (in the 1st part) or the additional text for the static caveat (2nd part). Thanks.

**Comment by bsnouffer** [comment]
Reviewed over email:

For the survey selectivity issue, I think what you have suggested all sounds good.

-Jason

**Comment by bsnouffer** [comment]
Inputted in FishPath. Closing.
