### ISSUE TITLE
Assessment inputs that are rarely known

### ISSUE THREAD

**Issue by NatalieDowling** [shcaba/FishPath-updates#268]
Assessment questions pertaining to quantities including
- virgin recruitment
- estimates of Umsy or Fmsy
- estimates of relative stock status
- F/M
- steepness

should be revisited in terms of the response options (are these ever going to be better than "borrowed or empirically derived"? They are almost never directly measured).

Also, we should point out in the descriptions that these are requirements for only a few assessment options, and more explicitly address the natural concern that such requirements appear to be counter-intuitive in data-limited assessments.

**Comment by shcaba** [comment]
I think that is part of the point-- these will likely never be better than "borrowed or empirically derived", which will throw out the red caution, as it should. No need to not make them red by changing the responses types.
You could imagine a meta-analysis across stocks/fisheries showing how many of the answers to a certain input gives reds, yellows or greens. These would almost always give red, thus strongly showing where we are at our weakest with inputs. 
You could even imagine on the FishPath website a reporting summarizing every question in FishPath, how many times it has been answered the distribution of the responses. This would be incredibly valuable info.

**Comment by NatalieDowling** [comment]
I love these ideas, Jason. Thank you.

**Comment by bsnouffer** [comment]
Closing. Seems like the behavior we want based on Jason's response.
