### ISSUE TITLE
Check "Retain Status Quo" option under Management Measures

### ISSUE THREAD

**Issue by serenalomonico** [shcaba/FishPath-updates#27]
This issue came up in Conil when the group was using the 15 step process to narrow down Management Measure results and investigating caveats of specific options. The group clicked on "Retain Status Quo" for the bocinegro fishery. 2 colored caveats were displayed ( one red and one orange). A “red” caveat was displayed because we answered “Yes” to “Has the nature of fishing operations changed or is the nature changing…?” question. FishPath Team Noted: Therefore, we should not keep status quo (check this relationship in FP)  - and think about how long the type of management should be implemented. Natalie to please review.

**Comment by bsnouffer** [comment]
Natalie is doing a full review of management measures caveats. These comments will be taken into consideration during the review.

**Comment by NatalieDowling** [comment]
The red caveat is appropriate. The wording is now "It is not advisable to retain the status quo management in the face of changed or changing fishing operations"

**Comment by bsnouffer** [comment]
Looks good. This wording has already been updated. Closing.
