### ISSUE TITLE
More description needed against "What time series exists of removal data for this fishery, and at what level of usability/completeness?"

### ISSUE THREAD

**Issue by NatalieDowling** [shcaba/FishPath-updates#270]
We need to add clarification around the following issues:

- how should users answer the question if they have excellent data on reported catch, but nothing on discards? Do we need to ask the user to make a judgement call based on the suspected discard:retained ratio?

- how should users answer the question for fisheries where species ID is an issue? The catch series might be well reported but the species identification may be incorrect. We could deal with this by asking a separate question about the ease and reliability of species ID and invoking orange caveats for options that use catch data or species composition data.

**Comment by shcaba** [comment]
These are points we definitely want to clarify. 
My opinion is that using the word "removal" should alert the user that the time series needs all sectors of removals-- whether it be commercial, rec, bycatch, etc.-- to be considered complete. This also goes for species ID issues that would bring large uncertainty to any portion of the time series. 

Here are some suggested edits:

1: Snapshots/intermittent/inconsistent reporting from all removal sectors, including bycatch
2: Time series with flaws such as missing years of major or peak catch, missing major fleets/metiers, gaps in recording significant dead bycatch, unresolved species identification issues, or is generally poorly sampled (i.e., high uncertainty). 
3. Partial time series that includes major/peak years of catches from major fleets/metiers and dead bycatch, and resolves any species identification issues (if present).

**Comment by NatalieDowling** [comment]
This looks good to me. Thanks Jason.

**Comment by bsnouffer** [comment]
Inputted updated answers to question (ID 251) into FishPath
