### ISSUE TITLE
Edits for "reviewing top options" process for the Assessment section

### ISSUE THREAD

**Issue by NatalieDowling** [shcaba/FishPath-updates#271]
Under Step 1, "Option Retention", for the Assessment component, we need to add the following:

"Sort by input category and hide options that are inferior to others that are available. For example, if quantitative assessment options are available, most or all of the "Expert Judgement" and "Empirical Reference Points" options can be excluded."

"Seek to avoid redundancy by narrowing down options that fall under the same input category. For example, the inclusion of multiple types of risk assessment is not necessary".

**Comment by shcaba** [comment]
Natalie and I have what I think is a better solution to this now. She will be sending out our new assessment tiers. If we are all good with that approach and figure out how best to present these tiers, we can do a simple modification to his reviewing top options verbiage.

**Comment by NatalieDowling** [comment]
Yes. Stand by, gang. Will send in next couple days.

**Comment by bsnouffer** [comment]
shared google drive spreadsheet from link Natalie sent:

https://docs.google.com/spreadsheets/d/1UeAxsh2ZlBgztO1tgqsh8c91zhjsvZqxxmJfIjiwYfA/edit#gid=1504552990

**Comment by bsnouffer** [comment]
The tool has been updated to include a column denoting the assessment 'tier'. It allows for sorting by tiers. Default ordering and initial autohiding of options has been updated for assessments as well. Now if a mid or high tier assessment method is available (meets all criteria), then all pre-assessments and data-poor assessments are hidden, regardless of whether they met all criteria. Available mid and high 'tier' assessments are placed at the top, followed by available pre and data-poor methods (hidden/greyed out), and ending with all eliminated methods at the bottom (also hidden).  Guidance for narrowing process in assessments has been updated to incorporate this new information. The user guide has been updated as well.
