### ISSUE TITLE
Provide guidance that can only drag and drop options if "customized sort order" is selected

### ISSUE THREAD

**Issue by NatalieDowling** [shcaba/FishPath-updates#273]
There is no explicit guidance that states this in the "review top options" process - you have to find this capability by luck if you happened to select "customized sort order". We should state this outright.

**Comment by NatalieDowling** [comment]
We should also explain up front what all the filters and sorting options are.

**Comment by bsnouffer** [comment]
Closing. The user guide provides instructions about filters and using drag and drop. 

There are also some small changes to the results display which will make it more clear what sort is being used (and if custom sort, to drag and drop to change the order of options), as well as possibly a legend being developed soon as discussed in #35.
