### ISSUE TITLE
Doesn't load on internet explorer

### ISSUE THREAD

**Issue by bsnouffer** [shcaba/FishPath-updates#277]
FishPath is not loading on Internet Explorer for me.

IE Version 11 using Windows 10. I haven't checked other versions or systems.

Might be related to updates of React and various packages.

**Comment by underbluewaters** [comment]
I haven't done any testing beyond Chrome and only occasionally Firefox. Do you know if it was working in IE before? 

FishPath is in need of a cross-browser support review before the public launch. I'm not sure IE11 would be on the list of supported browsers considering Microsoft is trying to move everyone to Edge (which is a lot easier to support).

**Comment by bsnouffer** [comment]
Developing for backwards comparability to IE would probably require a moderate amount of work. I have not encountered a user that only has IE. For now I would suggest not spending the time to make FishPath work on IE. If this is a pressing issue for a user, then we can reconsider, but as Chad noted, IE is being phased out. It should be alright to ask a user that only has IE to upgrade to Edge, Chrome or Firefox.

@serenalomonico, @dtdougherty: Any qualms against closing this, and reopening if necessary?

**Comment by bsnouffer** [comment]
Closing for now since no plans to address this given the reasoning above. We can reopen if necessary.
