### ISSUE TITLE
Deleted caveats still appearing in certain places

### ISSUE THREAD

**Issue by bsnouffer** [shcaba/FishPath-updates#278]
Question 1479 (High IUU) used to have some caveats for data collection options that have since been deleted. However, in the database they still appear as caveats with empty strings:

![Ex Deleted Cavs Format](https://user-images.githubusercontent.com/11687620/61900088-b33c9280-aed1-11e9-814c-dbb97e38c9a1.PNG)

This is causing them to be caught by some of the logic in the code: 

- They cause the question to appear in the data collection section of the questionnaire, even though the question does not have any caveats or criteria associated with data collection anymore.
- They appear in the affected options in the change answer pop up (see image below)
- They are affecting the output of the new exports (not yet deployed)
- I haven't done a full search so potentially affecting other areas

They do NOT show up in the results display, which is the correct behavior.

In the admin section, they look to be completely deleted. This may be legacy from an old way of saving deleted caveats. 

Another example of a deleted caveat in the database appears as:
![image](https://user-images.githubusercontent.com/11687620/61900695-fba88000-aed2-11e9-817f-7656a4c0eaeb.png)

I believe this is the new way of saving deleted caveats. This way of saving is handled properly in the above examples from what I can tell.

Possible fixes:

1. Update code to handle this format as well
2. Manually "redelete" any examples of this so that they are removed from the database and saved in the same way as the 2nd example (assuming that is the new way of saving)
3. Update handling deleting caveats to completely remove it from database (would be good to do the similar with criteria as well, deleted criteria appear as null in the database)

My suggestion would be to do option 2 for the short term and explore option 3 as a long term solution

In change answer pop up:
![image](https://user-images.githubusercontent.com/11687620/61900430-702eef00-aed2-11e9-939b-93597cc0e9a4.png)

**Comment by underbluewaters** [comment]
Thanks for the detailed notes Brian. I went ahead and made some changes to CaveatEditor to prevent caveats with empty titles from saving. I **think** this is the only place that needs changing, but it could crop again if I missed something.
https://github.com/mcclintock-lab/FishPath/commit/2a1f4df16555f3dfa15518ad6b349ccce5581144

I manually deleted all the caveats with empty titles so those at least won't be a problem for now.
