### ISSUE TITLE
New Question regarding in-season monitoring or temporal management

### ISSUE THREAD

**Issue by serenalomonico** [shcaba/FishPath-updates#28]
Suggestion to add a new question regarding in-season monitoring or temporal management options. Example "Do you have the capacity for in-season monitoring and subsequent appropriate adjustment?". This will need a complete list of caveats against each option in FP. Put a yellow if it’s not a boom and bust species.

Full background for context:
In Conil under the "Temporal Management" category in Management Measures results, the group investigated 3 options that were cautioned against. Natalie believed that these wouldn’t be a great idea for the fishery and then asked for group feedback. The 3 were: Time of day restrictions; Fixed season duration or number of fishing days; Adjustable season duration. When asked how they felt about eliminating or hiding these options, the group answered that bocinegro doesn’t have a specific fishing season – it can be fished year-round. There’s a seasonal decline of catches (Dec, Jan, Feb) largely because of the meteorological conditions / poor weather where they can’t fish. 

Digging deeper into the option “Adjustable season duration”: The description of this option has the information that should be read closely and then can be applied specifically for your fishery. This rule is the case with highly productive species, which doesn’t apply to bocinegro. Overall, the group decided to hide all the temporal management options.

**Comment by bsnouffer** [comment]
Discussed with Jason and Natalie and agree that this issue is closely related to #118. We agree that the question suggested in #118 should be added and that this aspect should be included in that new question. Closing this in favor for 118.
