### ISSUE TITLE
add ability to search for fisheries from admin side

### ISSUE THREAD

**Issue by bsnouffer** [shcaba/FishPath-updates#281]
Allow for searching for a specific fishery from the list instead of having to scroll through the list

**Comment by bsnouffer** [comment]
Came up as an idea for a useful feature in a workshop when wanting to find a fishery that was created 2 years ago. 

Listed as idea in #149, but keeping open for now to track the searching specifically if not addressed when doing 149

**Comment by underbluewaters** [comment]
We’ll have to be careful with the implementation here since the responses
are in dynamodb. Would require a full table scan as it’s structures now
which could get expensive. Alternatively we could build some sort of
separate index but I haven’t done that yet with this sort of database.

**Comment by dtdougherty** [comment]
This would be incredibly useful. I basically give up trying to find a fishery created at a workshop over a month ago. Maybe having specific date shown would help? Or does that change each time it is edited?

**Comment by bsnouffer** [comment]
Added the ability to search by username (email) in the admin side: mcclintock-lab/FishPath#108. Closing, if more complex searching is needed, we can reopen.
