### ISSUE TITLE
Consider removing HCR label in results

### ISSUE THREAD

**Issue by bsnouffer** [shcaba/FishPath-updates#283]
Currently in the management measures section, there is a header label that reads, "Harvest Control Rule Options". It is inconsistent with the title of the section and with the other sections which just have "Option" as the header label. This would need to be updated in the code.

![image](https://user-images.githubusercontent.com/11687620/62901545-ec6a6480-bd11-11e9-88ed-bccc919d0b5f.png)

![image](https://user-images.githubusercontent.com/11687620/62901589-0ad06000-bd12-11e9-8f8a-cf71b5abe58a.png)

**Comment by dtdougherty** [comment]
Agreed, this should be updated to just read "Options"

**Comment by bsnouffer** [comment]
fixed in mcclintock-lab/FishPath#57
