### ISSUE TITLE
Review Assessment Section "Depletion Analysis" caveat for boom-and-bust species

### ISSUE THREAD

**Issue by serenalomonico** [shcaba/FishPath-updates#295]
Current **Red** Caveat: 
Q: Does the species follow a boom-and-bust population cycle?
A: No
Caveat: Depletion analyses are typically applied to species with rapid growth rates, short life-spans, little generation overlap and weak or no stock-recruitment relationships. The approach assumes high steepness, a closed population (i.e. negligible recruitment, and immigration/emigration), and no within-season natural mortality.

**Comment by NatalieDowling** [comment]
Hi Serena, 
Just got the notification that this task has been assigned to me. It's not clear what the actual issue is with this item.  Please could you clarify?
Thanks,
Natalie

**Comment by dtdougherty** [comment]
Agree with Nat's comment, what is the issue, is this a proposed new wording to a caveat that needs to be reviewed? Un-tagging Jono and tagging Serena and Brian for clarification.

**Comment by serenalomonico** [comment]
Good question - Jono had brought this up previously, just resent his email.

**Comment by bsnouffer** [comment]
Adding the email here so everyone can see and doesn't get lost in peoples inboxes:

> My question was centered on why there is a red caveat for depletion analysis if the species does not follow a boom/bust life cycle.  My only experience with depletion analysis was reviewing an application of the method to lobster, performed by Beth Babcock. It seemed an appropriate use of the method, but I would not characterize lobster as boom/bust.
> 
> Im questioning whether it should be a red caveat, and perhaps even a caveat at all. Seems like it could be just as easy to track CPUE within a season for a species that is not boom/bust… Also, if im not mistaken, one use of depletion analysis would be to set a TAC in the following year based on estimating the current year starting biomass (and depletion) from an entire season of data. If you were dealing with a boom/bust species, then the current years starting biomass estimate might not be the best predictor of the next years starting biomass…
> 
> Thoughts?
> 
> Jono

**Comment by shcaba** [comment]
I don't know of any requirement for DeLury or Leslie depeltion estimators to be specifically for boom-bust stocks. As Jono has mentioned, I too have seem these types of approaches used for spiny lobster, and different than the example he gave.
The caveats for this method are if you measure catch or effort poorly, you can get biased estimates of the unfished size of the stock (K).  Catchability may change through time as the population decreases, also causing biased K estimates. The assumption of a closed population may cause bias depending on what version of the depletion analysis one uses.  

I would remove that caveat from this method.

**Comment by NatalieDowling** [comment]
I agree with Jono and Jason - and sorry, Jono, I had meant to see this one through much earlier when you first had replied. I think this one was down to me being naive and overzealous back in the day. I’m happy for the caveat to be removed.

**Comment by NatalieDowling** [comment]
If anything, we could add something in the description to say that this method has been successfully applied across a range of life histories, including boom-and-bust, but I’m not at all wedded to this.

**Comment by bsnouffer** [comment]
Removed the red caveat. There is also a green caveat that says the same thing when answering "yes". Sending back to Jason to decide if that should remain or be removed as well.

Current **Green** Caveat:
Q: Does the species follow a boom-and-bust population cycle?
A: Yes
Caveat: Depletion analyses are typically applied to species with rapid growth rates, short life-spans, little generation overlap and weak or no stock-recruitment relationships. The approach assumes high steepness, a closed population (i.e. negligible recruitment, and immigration/emigration), and no within-season natural mortality.

**Comment by shcaba** [comment]
I think we get rid of the green caveat as well, right? Depletion analysis isn't just for boom or bust, so neither a good or bad caveat.

**Comment by NatalieDowling** [comment]
I don't see the harm in the green for boom-bust, because the assumptions around the method, and the fact that it can be used as a within-season analysis, do mean that it can suit this type of life history, where other types of assessments may not. But I'd be happy to lose the green and just move this kind of text to the description.

**Comment by bsnouffer** [comment]
Based on Natalie's comment, I think it makes sense to leave it in. The green caveat isn't penalizing non-boom or bust fisheries, but is flagging that it might be better suited for boom and bust. 

Closing issue for now, but feel free to reopen if someone thinks that the green should be removed.
