### ISSUE TITLE
Update welcome page text

### ISSUE THREAD

**Issue by bsnouffer** [shcaba/FishPath-updates#299]
Current: "Welcome to the FishPath Tool!
The goal of the FishPath tool is to guide the selection of context-appropriate management strategies by identifying options for data collection, stock assessment, and management measures. Once registered, you may access the FishPath tool, including the FishPath questionnaire, interactive results tailored to your fishery, and supporting resources."

Note: the same text is shown whether or not you are logged in

**Comment by dtdougherty** [comment]
This seems okay to me, I guess we could just remove the words "once registered" for those that are already logged in, but keep the rest. Were we thinking of adding more here? I think simple is good.

**Comment by serenalomonico** [comment]
@dtdougherty - small changes below. Kept "once registered" and changed to harvest strategy.

Welcome to the FishPath Tool! The goal of the FishPath tool is to guide the selection of context-appropriate harvest strategies by identifying options for data collection, stock assessment, and management measures. Once registered, you may access the FishPath tool, including the FishPath questionnaire, interactive results tailored to your fishery, and supporting resources.

**Comment by bsnouffer** [comment]
fixed in mcclintock-lab/FishPath#57
