### ISSUE TITLE
Define or provide alternate term for "steepness" 

### ISSUE THREAD

**Issue by bsnouffer** [shcaba/FishPath-updates#307]
In going through the questionnaire with Anthony from San Andres:
Steepness is a term that is confusing to those that do not work closely with stock assessments. Consider adding a description or other terminology to question 190: "Do you have an estimate of steepness for the species? If so, how was this obtained, and with what degree of certainty?"

Discussed that we could change to something like "recruitment compensation (ie: steepness)"

**Comment by shcaba** [comment]
Updated question to say

"Do you have an estimate of recruitment compensation (i.e, termed "steepness" in some stock-recruit relationships) for the species? If so, how was this obtained, and with what degree of certainty?"

A taxanomically-derived value for steepness can be found for many species using the FishLife tool:
https://github.com/James-Thorson/FishLife

**Comment by bsnouffer** [comment]
I should have included the description in the original issue description. It lists the FishLife tool. So just an update to the question is needed based on your response.

Current question description :
"A common measure of stock resilience, steepness is defined as the fraction of recruitment from a virgin or unfished population obtained when the spawners are at 20% of the virgin level. This value is a required input for some assessment methods. If you do not currently have an estimate of this value, the following link may provide a tool or source of information to get an estimate:
 https://github.com/James-Thorson/FishLife "

**Comment by dtdougherty** [comment]
It sounds like we just need to update the question to:
"Do you have an estimate of recruitment compensation (i.e, termed "steepness" in some stock-recruit relationships) for the species? If so, how was this obtained, and with what degree of certainty?"

Leaving the description the same:
"A common measure of stock resilience, steepness is defined as the fraction of recruitment from a virgin or unfished population obtained when the spawners are at 20% of the virgin level. This value is a required input for some assessment methods. If you do not currently have an estimate of this value, the following link may provide a tool or source of information to get an estimate:
https://github.com/James-Thorson/FishLife "

**Comment by dtdougherty** [comment]
Jason, re-tagging you just to okay the comment above, then we can push through

**Comment by shcaba** [comment]
That looks great.

**Comment by bsnouffer** [comment]
added to FishPath. @shcaba leave the issue open until it gets put into FishPath. (whoever inputs it and moves the issue to communication will be the one to close the issue.)
