### ISSUE TITLE
Review or add caveats for Management Measure category "Gear Management" 

### ISSUE THREAD

**Issue by serenalomonico** [shcaba/FishPath-updates#31]
In Conil, the FishPath Team noted: Add caveat trigger to "gear management". Input controls do not put direct controls on fishing mortality. For example, gear restrictions do not directly control for levels of fishing mortality (add this in). Useful for multispecies fisheries. 

The "Gear Management" category in Management Measures includes 2 options: "By selectivity" and "Unrelated to selectivity".

This issue needs expert review: what is color of caveat, which questions trigger this caveat or is this static?

**Comment by bsnouffer** [comment]
Natalie is doing a full review of management measures caveats. These comments will be taken into consideration during the review.

**Comment by NatalieDowling** [comment]
I have added a static caveat to each input control, along the lines of "Gear management, like other input controls, does not directly control fishing mortality".

There is already a green caveat for all input controls against the question asking whether the fishery is multispecies, stating that input controls are often preferable to output controls in multispecies fisheries.

**Comment by bsnouffer** [comment]
Full text of static caveat for both gear mgmt options: "Gear management, like other input controls, does not directly control fishing mortality. Caution should be exercised in that, even when input controls are well-calibrated to sustainable levels, fishers can still increase their catch by scaling up all unregulated inputs ("capital stuffing") to increase their harvesting power in the face of regulations."

Reviewed and inputted into FishPath.
