### ISSUE TITLE
Exports: add category to all

### ISSUE THREAD

**Issue by dtdougherty** [shcaba/FishPath-updates#310]
The exports in the admin section are awesome. When downloading caveats by questions for each section, I noticed that the DC section included the option category, but the MM section did not. It would be nice to list option category for each section

**Comment by bsnouffer** [comment]
Ah yea. I added category for the DC section because it is needed to identify between options of the same name. I will add category for assessment and MM sections for both the cavXq and critXq reports.

**Comment by bsnouffer** [comment]
fixed in Fixed in mcclintock-lab/FishPath#59

also included question description to the two question order exports per Serena's request
