### ISSUE TITLE
Static caveats added - catch-only methods compromised if using catch control rules.

### ISSUE THREAD

**Issue by NatalieDowling** [shcaba/FishPath-updates#315]
Changes made in FishPath during Coaches Network workshop - review required

**Comment by bsnouffer** [comment]
New static caveat:

>  If catch controls are used, or are to be used as a management measure, these compromise the use of catch time series as an informative assessment input.

Options caveat was added to:
- BRT
- ORCS
- DCAC
- DB-SRA
- SSS
- SRA
- Feasible stock trajectories
- qR method
- OCOM
- COM-SIR
- SSCOM
- XSSS
- XDB-SRA

Other catch only methods caveat not added to:
- Analysis of changes in the spatial distribution of catch
- CUSUM Control Charts
- Sequential catch triggers

**Comment by bsnouffer** [comment]
@shcaba can you provide a quick review of this when you get a chance. Changes have already been put into the tool during the training, so if it looks good, then you can move it directly to the communication column. Thanks.

**Comment by NatalieDowling** [comment]
The three "catch only" methods to which the static caveat was not added were excluded because catch limits do not necessarily impact their value:
•Analysis of changes in the spatial distribution of catch - valid regardless of catch controls, unless these are spatial, but even then, effort may be reported at a finer spatial scale than that of the controls
•CUSUM Control Charts - may not even use catch data
•Sequential catch triggers - presumably if there were catch limits in place, a trigger system would have trigger values set well below, or at, the limit.

We can add static caveats to these effects, if felt this was desirable.

**Comment by shcaba** [comment]
I think we could say it "may compromise" as many of those methods are dynamic approaches. What it depends on is the estimate of stock status going into the model. The west coast uses XSSS, XDBSRA, SSS, DBSRA as dynamic estimators despite catch control rule implementation. The reason this is fine is that these models have production curves and population dynamics models. DCAC does not do this, as it is an analytical estimator.  I would say the first three methods definitely fit this caveat, whereas the rest are less affected.

**Comment by bsnouffer** [comment]
Jason provided me with further detail in an email:

I actually do not think that it will matter all that much for the other ones. We can talk with Natalie about it, but the point of moving from something like DCAC to DBSRA was to make it dynamic and updatable.  
Here is my overall summary (? means I do not know):

- **BRT (likely matters)**
- **ORCS (matters)**
- **DCAC (matters)**
- DB-SRA (probably doesn't matter)
- SSS  ( probably doesn't matter )
- SRA  ( probably doesn't matter )
- Feasible stock trajectories  ( probably doesn't matter )
- qR method (?)
- OCOM (?)
- COM-SIR  ( probably doesn't matter )
- SSCOM  ( probably doesn't matter )
- XSSS  ( probably doesn't matter )
- XDB-SRA  ( probably doesn't matter )


@NatalieDowling - Would you be alright with removing the static caveat for the options Jason has listed as "probably doesn't matter" or would you suggest a different possibility?

**Comment by NatalieDowling** [comment]
Thanks Brian and Jason and apologies for the delay. Jason is totally correct. The static caveat can be removed from those listed as "probably doesn't matter". I think it likely does matter for OCOM and qR.

**Comment by bsnouffer** [comment]
Pinged Jason about this and he said go ahead with the changes suggested. I will remove the static caveat from all the methods listed as "probably doesn't matter". I will leave it in place for BRT, ORCS, DCAC, qR, and OCOM.

**Comment by bsnouffer** [comment]
Inputted into FishPath

**Comment by NatalieDowling** [comment]
Great; thanks Brian!
