### ISSUE TITLE
Various minor FishPath edits made during Coaches Network workshop

### ISSUE THREAD

**Issue by NatalieDowling** [shcaba/FishPath-updates#316]
Made the following changes in response to feedback during the Coaches Network - these require review:

- Wording changed in title of Management Measure "Catch - adjusted by fixed proportions without feedback".
- Added caveat to Management Measure options of adjusting catch or effort based on assessment of closed areas - that this won't be feasible if there are no closed areas.
- Added cautionary caveats to gear-based management measures cautioning against them if enforcement capacity, or extent of fisher cooperation, are low.
- Added a cautionary caveat against "Levy fishery taxes" if the fishery is subsistence.
- For sex-specific and size-based management measures, added orange cautionary caveats if compliance capacity is low, or if the fishery is small-scale subsistence.
- Added cautionary static caveats against size limit management measures to say that these may harder to impose if the gear is nets, and that size limits may need to have associated gear restrictions to make them achievable.
- Changed wording of "Permanent no-take closures" to "Permanent (year round) no-take closures"
- Clarified wording of "Temporal closures - fixed seasonal" and "Spatial closures - by area" to make these more explicit in attempt to reduce confusion.
-

**Comment by bsnouffer** [comment]
Adding specifics of changes.

1) Wording changed in title of Management Measure "Catch - adjusted by fixed proportions without feedback".
    - updated to "Adjust by fixed proportions, in response to qualitative assessment, without feedback control rule"
2) Added caveat to Management Measure options of adjusting catch or effort based on assessment of closed areas - that this won't be feasible if there are no closed areas.
    - For question: "Are there no take reserves..." 
      - Red caveat added to catch based "Unable to use this method if no closed areas exist."
3) Added cautionary caveats to gear-based management measures cautioning against them if enforcement capacity, or extent of fisher cooperation, are low.
    - For both gear based mgmt ("By selectivity", "Unrelated to selectivity") added the following caveats
      - For answer "Low" to question "what is the extent of enforcement capacity?"
        - Yellow caveat: "May be difficult to control if the enforcement capability is low. This approach should also be augmented by measures that address effort creep."
      - For answer "Low" to question "What is the level of cooperation in the fishery..."
        - Yellow caveat: "May be difficult to control if the level of cooperation is low. This approach should also be augmented by measures that address effort creep."
4) Added a cautionary caveat against "Levy fishery taxes" if the fishery is subsistence.
    - For question "Categorize nature of fishery in terms of main market activity?" added to the following answers the caveat: "Not recommended to impose levies in small-scale fisheries"
      - Red for answers "Small scale recreational", "Subsistence"
      - Orange for "Subsistence - artisanal (local markets only)", "Large-scale recreational"
5) For sex-specific and size-based management measures, added orange cautionary caveats if compliance capacity is low, or if the fishery is small-scale subsistence.
    - New orange caveat: "May be difficult to control if the level of cooperation is low. This approach should also be augmented by measures that address effort creep."
    - Added to all 6 size and sex-specific based management options for answer of "Low" to question "...level of cooperation within the fishery, in terms of current compliance..."
6) Added cautionary static caveats against size limit management measures to say that these may harder to impose if the gear is nets, and that size limits may need to have associated gear restrictions to make them achievable.
    - Static caveat added to all 3 size limit options: "Size limits may be harder to achieve with net fishing"
    - Static caveat added to all 3 size limit options: "Appropriate gear restrictions should be considered to maximise the effectiveness of size limits."

7) Changed wording of "Permanent no-take closures" to "Permanent (year round) no-take closures"

8) Clarified wording of "Temporal closures - fixed seasonal" and "Spatial closures - by area" to make these more explicit in attempt to reduce confusion.
    - "Temporal management - seasonal closures" updated to "Temporal management - Seasonal closures (of whole fishery)" (ID: 87)
    - "Spatial management - Fixed seasonal closure" updated to "Spatial management - Fixed seasonal (area-specific) closures" (ID: 81)

**Comment by bsnouffer** [comment]
@NatalieDowling, I was reviewing as I entered the specifics above. I know these were discussed during the workshop, so I focused less on the content and more on wording and making sure that they covered all the options mentioned. Overall, I think it looks good. I think the updates to the option names work well.

I did find two places were it looks like you may have missed an update or it didn't save correctly.

For item 1)
- _Should the same option in effort limits category be updated to match as well?_

For item 2)
  - _I don't see the same caveat added to the effort based option, its only listed on the catch based option._

**Comment by NatalieDowling** [comment]
Thanks Brian. 

Re: Item 1) YES - I thought I had caught that, but apparently not. 
Re: Item 2) Oops. Again, I thought I had done so. May have been dodgy hotel internet not saving, or may have been me.

Let me know if you would like me to fix both. Thanks.

**Comment by NatalieDowling** [comment]
Took liberty of addressing both.

**Comment by NatalieDowling** [comment]
Took liberty of addressing both.

**Comment by bsnouffer** [comment]
Looks good. Thanks!

**Comment by NatalieDowling** [comment]
De nada!

BTW am having a little trouble getting onto the Content Issue Project Board. Am using the link https://github.com/shcaba/FishPath-updates/projects/2 as per your Google Doc, but it’s spinning its wheels and not loading. Am I doing something wrong?

Thanks!
