### ISSUE TITLE
"Comm-industrial" not listed as satisfying criteria for vol. logbooks - biol. info.

### ISSUE THREAD

**Issue by bsnouffer** [shcaba/FishPath-updates#319]
Commercial - industrial is not listed as satisfying criteria for Voluntary Logbooks - Biological Information.

It is listed as satisfying criteria for every other option in data collection that the "Categorize the nature of the fishery..." question is used for criteria. 

I will update the criteria to include commercial - industrial for this option.

**Comment by bsnouffer** [comment]
@NatalieDowling can you just confirm that this was simply missed and not intentionally done for some weird reason. Thanks.

**Comment by NatalieDowling** [comment]
This was actually deliberate in the first instance - the thinking being that voluntary logbooks are likely to be of all shapes and forms across a large commercial industrial fleet, and that formal logbooks were the more sensible (and commonly used) option. BUT given it's a criteria question, and the exclusion is only for the biological data, then I say go ahead and greenlight it.

**Comment by bsnouffer** [comment]
Ah right, I think I remember this being discussed awhile ago. Agreed that it is weird that it's only for the biological data category. And to me it doesn't make sense that it would fail the criteria due to this as it can still be done, just usually formal logbooks are used. Maybe it should instead be added as a caveat, or put into guidance docs in the toolkit?

**Comment by NatalieDowling** [comment]
Agree with Brian's email, which went, "Ah right, I think I remember this being discussed awhile ago. Agreed that it is weird that it's only for the biological data category. And to me it doesn't make sense that it would fail the criteria due to this as it can still be done, just usually formal logbooks are used. Maybe it should instead be added as a caveat, or put into guidance docs in the toolkit?" Let's include as a static caveat - and definitely remove the "fail" criterion outcome.

**Comment by NatalieDowling** [comment]
Want me to do it? Let me know.

**Comment by bsnouffer** [comment]
I was leaning towards a yellow caveat triggered by the answer "comm-ind" instead of static because this concern is specifically is about voluntary logbooks for commercial-industrial fisheries, not the option in general no matter the type of fishery. If "comm-ind" is answered, it could say something simple along the lines of  "Given that this is a commercial-industrial fishery, consider implementing formal logbooks instead if resources allow." (Or with more detail if you want to add/edit)

However, there is already a static caveat in voluntary logbooks that states "Although voluntary logbooks may provide valuable fishery information, potential reporting biases must be accounted for." Another option could be to add to that and say something like,  "Although voluntary logbooks may provide valuable fishery information, potential reporting biases must be accounted for.  _If resources allow, formal logbook programs can help remove these biases._"

Let me know your thoughts. Please change/edit either of these as you see fit.

**Comment by NatalieDowling** [comment]
Have taken liberty of removing criteria and adding caveats. For review.

**Comment by NatalieDowling** [comment]
I’ve gone ahead and added it as a yellow caveat to large-scale rec, comm-ind and comm-art, for all 4 categories of info.

I think the static caveat can stand as is. How’s that?

**Comment by bsnouffer** [comment]
Looks good to me. Thanks for updating.
