### ISSUE TITLE
Clarify length of supply chain in Question 2351

### ISSUE THREAD

**Issue by serenalomonico** [shcaba/FishPath-updates#32]
2351: How many levels of buying/distribution does this fishery have (i.e., how many nodes in the supply chain)?
The greater the number of levels (or points) in the supply chain, the more difficult it may be to establish representative sampling for market, sales, or processor-based data collection programs.

FishPath Team: Recommended that a question wording clarification is needed about supply chain levels and where it begins and ends in this (ends with final consumer?). Edit description.

**Comment by NatalieDowling** [comment]
Edited as suggested. Please check.

**Comment by serenalomonico** [comment]
Thanks @NatalieDowling - looks good.
