### ISSUE TITLE
"Flagged Questions" results page header

### ISSUE THREAD

**Issue by serenalomonico** [shcaba/FishPath-updates#320]
Minor issue: In the Results Page Header, it says “Flagged Questions / “These answers were flagged for later review.” Since we use term “bookmark” in the questionnaire, for consistency, consider changing to “Bookmarked Questions / These answers were flagged in the questionnaire with the Bookmark feature for later review”.

**Comment by bsnouffer** [comment]
Completed in mcclintock-lab/FishPath#70

**Comment by bsnouffer** [comment]
Update screenshots in user guide
