### ISSUE TITLE
Order of bookmarked & influential answers questions in results page

### ISSUE THREAD

**Issue by serenalomonico** [shcaba/FishPath-updates#322]
In Flagged /Bookmarked Questions and Influential Answers Section, fix in same order as questionnaire order.

**Comment by bsnouffer** [comment]
The influential answers section is ordered by the most influential to least and I think that this makes sense for that section.

The flagged questions is ordered by question id. Agreed this makes little sense and could be changed to follow questionnaire order, or maybe ordered by category like the answers page.

Also, the flagged questions are above the influential answers. As a large number of questions can be bookmarked, and the importance of seeing influential answers when looking at results, I suggest that the influential answers section is moved to be above the flagged questions.

**Comment by serenalomonico** [comment]
Thanks @bsnouffer : 
- Agree leaving influential answers order as is, thanks for pointing out.
- My vote is to order by questionnaire order instead of by category.
- Good note, I can go either way on the order of influential vs. bookmark sections. Sometimes it's helpful to see the flagged ones immediately in case you want to change any answers.

**Comment by bsnouffer** [comment]
Updated bookmarked section to be in the same order as the questionnaire. Left the bookmarked section above the influential answers section. Would be easy to switch in the future if desired.

Completed in mcclintock-lab/FishPath#70
