### ISSUE TITLE
Update question about time series for no-take zones

### ISSUE THREAD

**Issue by bsnouffer** [shcaba/FishPath-updates#323]
Regarding question 287: What time series exists of fishery-independent sampling inside and outside of no-take zones?

According to Jason, "papers have shown that you probably need to wait about 10 years until you can even start sampling within the no-take" and we should consider updating either the answers or the question description to reflect this.

Currently the answers are the same as for other survey data questions:
0: Absent
1: Snapshots/intermittent/inconsistent reporting
2: Partial time series that does not cover major or peak years of removals
3: Partial time series that cover major/peak years of removals
4: Full time series since fishing began

The question description: 
This question refers to scientifically designed data collection programs with sampling inside and outside of no-take zones. This might include, for example, programs to determine species density and/or size, with sampling inside and outside no-take zones.

**Comment by bsnouffer** [comment]
Reviewed the papers Jason sent me regarding this (Babcock and MacCall 2011, McGilliard et al. 2011) as well as Wilson et al 2010. Here are some brief notes about their discussions regarding using data before fully established.

_McGilliard et al._: For their simulations: Ran models for a various M and h combinations. Fished down stocks over 60 years. Established no-take MPA. Implemented density ratio control rule (DRCR) method 5 years after MPA established. Found that it took about 15-20 years after MPA established before ratios in and outside tracked depletion. Noted Wilson et al 2010 might have a way to account for this.

_Wilson et al._: Noted that you need to make sure the MPA has rebounded to approx K, however they do offer a method to determine a "phase in" period if starting method before MPA has fully recovered. Fortheir model, they choose the mean generation time as the amount of time it would take for the MPA to be considered fully recover. (For their modeled species, it was 10 years)

_Babcock and MacCall_: For their simulations: Fished down stock for 50 years. Implemented MPA and density-ratio control rules in same year. In early years before the MPA could rebuild densities, control rules stipulated to increase effort as the density ratios were higher. This showed potential downside (or need for a 'phase in') when using MPA ratios before well established.

Seems like its tough to put a number on how long you need to wait before using this data. Wilson et al. also shows that it is possible to use the data while the no-take is rebuilding. Given that, here is my suggestion for updating the question. Changes in bold. 

Question:  "What time series exists of fishery-independent sampling inside and outside of no-take zones?"

Description: This question refers to scientifically designed data collection programs with sampling inside and outside of no-take zones. This might include, for example, programs to determine species density and/or size, with sampling inside and outside no-take zones. **This data is most effective when the no-take zone has had time to fully recover to biomass levels near carrying capacity and is fully enforced. Recovery can take a wide range of years depending on the species being surveyed and stock status when the no-take zone was implemented. Wilson et al. (2010) demonstrates a possible method for accounting for a newer no-take zone when using this data. If this data has been collected, but the no-take zone is newer or not well enforced, then you should answer 1.**

Answers:
0: Absent
1: Snapshots/intermittent/inconsistent reporting, **the no-take zone has not had time to fully recover, or is not well enforced**  
2: Partial time series that does not cover major or peak years of removals
3: Partial time series that cover major/peak years of removals
4: Full time series since fishing began

**Comment by bsnouffer** [comment]
Email from Jason:
Hi Brian,

The 10 year rule was going around for a while, but I think you have some good details here that provide more guidance than we currently have, so I would go with what you have here.
Nice job!

-Jason

**Comment by jonowilson** [comment]
Looks great to me. Thanks all
