### ISSUE TITLE
Old language that needs removal in question regarding current available assessment

### ISSUE THREAD

**Issue by shcaba** [shcaba/FishPath-updates#337]
The question is:
Do stock assessments suggest that overfishing is probable, for any species harvested?

The advice currently says:
Overfishing is the level of fishing mortality which depletes a fishery by catching so many adult fish that not enough remain to breed and replenish the population. **If no stock assessment has been conducted for the fishery, answer “No”.**

The last sentence is leftover from when we did not have the "unassessed" option, and should be removed.

**Comment by bsnouffer** [comment]
Good catch and agreed. Since "unassessed" is now an answer, I think the sentence bolded above can be completely removed and doesn't need any replacement. I will remove it from FishPath.

**Comment by bsnouffer** [comment]
Done. Closing issue. No communication needed.
