### ISSUE TITLE
Revisit the use of the word "measure" when referring to natural mortality

### ISSUE THREAD

**Issue by shcaba** [shcaba/FishPath-updates#357]
This is a comment from Andre, preferring the word "estimate" as we can never truly measure natural mortality.
This should be a simple fix in the answers of the Assessment section, where we replace "Measured" with "Estimated". 
For instance, "Estimated, with low to moderate uncertainty"
The questions themselves are fine, as we did use "estimated".

**Comment by bsnouffer** [comment]
The following data availability questions share the answers set containing "measured". Discussed with Jason, and decided that we can safely replace "measured" with "estimated" in the answers for each. None of the questions, or descriptions, use "measured." 

**Answers:**
0: No
1: Borrowed or empirically derived
2: Measured, but with high uncertainty (e.g. low sample size, outdated data, sampling from a small area of a bigger spatial scale, or unable to differentiate gender-specific values)
3: Measured, with low to moderate uncertainty (e.g., good sample size, up to date, covers the spatial range of the species)

**Questions using those answers:**
1. M/k
2. M
3. Maturity ogive or size-at-maturity relationship
4. length-fecundity relationship
5. steepness
6. von Bertalanffy growth parameters
7. current absolute stock abundance
8. Umsy ro Fmsy
9. r and K
10. virgin recruitment
11. Fmsy/M
12. length-weight relationship
13. (sigmaR - answers recently updated from measured to species specific, with high or low uncertainty) (#371)

**Comment by bsnouffer** [comment]
Inputted into FishPath. Closing.
