### ISSUE TITLE
Add SPiCT to the Production model options

### ISSUE THREAD

**Issue by shcaba** [shcaba/FishPath-updates#360]
This can just be added as a tool link and reference:

Tool: https://github.com/DTUAqua/spict

Pedersen, M.W., Berg, C.W., 2017. A stochastic surplus production model in continuous time. Fish and Fisheries 18, 226–243. https://doi.org/10.1111/faf.12174

**Comment by shcaba** [comment]
And we should also add the FRDC toolbox here, as they have several other methods that we don't need to list out, but give JABBA and SPiCT as examples and links (we can add my tool as an example of an age-structured production model later), then point to this toolbox for a more comprehensive list of options.

**Comment by shcaba** [comment]
http://toolbox.frdc.com.au/

**Comment by bsnouffer** [comment]
There are plans to put the FRDC toolbox (as well as other toolboxes) at the top of the Assessment reference page and to list it in all options that the FRDC toolbox has resources for.

**Comment by shcaba** [comment]
We also need to update the link to ASPIC: https://nmfs-fish-tools.github.io/ASPIC/

**Comment by bsnouffer** [comment]
The Production Model description got a big overhaul based on peer reviewer comments. These links were all added as part of that update. The FRDC link was added to a couple other relevant option descriptions as well and the nmfs toolbox links were updated in all options it was listed.
