### ISSUE TITLE
CUSUM Control Chart code or links

### ISSUE THREAD

**Issue by serenalomonico** [shcaba/FishPath-updates#37]
Jason added code or links to many Assessment options, and asked Natalie to track down a few, including this one. 

Natalie, please follow-up to ask the author if there is code or an app for Assessment Option "CUSUM Control Charts". 

Then, add the following EXAMPLE line in the option description: 
"The following link may serve as a useful resource for this assessment option: http://www.datalimitedtoolkit.org/"

**Comment by NatalieDowling** [comment]
I've added a link to the cusum function in R, and to R scripts from Mesnil and  Petitgas (2009)
