### ISSUE TITLE
Wording Revision for 2 Questions in MM Section

### ISSUE THREAD

**Issue by serenalomonico** [shcaba/FishPath-updates#377]
During a virtual workshop for concha negra, a mangrove clam, in northern Peru on 11 Dec. 2020, two questions really hung the group up. Although facilitation can be used to get the group through, suggest we aim to reword or consolidate -

ID: 1134. Is there a lack of knowledge or data about the fishery, which makes it difficult to inform a management measure?
This cautions against misapplication of stringent controls, and recommends precautionary control rules and improved information gathering. The questionnaire sections on Data Collection and Assessment may be helpful in addressing this question. 

ID: 1083. Is data collection difficult? 
Answer "Yes" if any of the following apply: 1) The fishery lacks formal data collection protocols, or they are poorly-designed or implemented; 2) Certain management actions would be difficult to enforce given the lack of data to determine the extent of compliance; 3) Data collection is patchy or inconsistent, either across time or space or with respect to gear type(s)/fleet(s) sampled; 4) There is a lack of reliable data or a lack of reliable empirical performance indicators for the fishery.

**Comment by bsnouffer** [comment]
Based on peer review comments and this issue, Natalie and I have reviewed these two questions along with other similar questions 1115 and 1030.

1115:Is there a high degree of uncertainty in the indicator(s), whether direct (empirical) or determined by assessment, on which a management measure may be based?
1030:Is it possible to calculate, or define a proxy for, a target, limit, or trigger reference points?

We decided that 1115 really gets at the heart of the matter, which is having high uncertainty in the indicators. Difficult data collection and lack of knowledge both get ultimately result in that. Given the confusion to these questions in the GH issue and peer review comments, we feel like this is best captured using strictly the one more explicit question 1115. 1134 and 1083 have been deleted and 1115's description and caveats have been revised slightly to capture any missing aspects from 1083 and 1134. [Details in this worksheet](https://docs.google.com/spreadsheets/d/16fnLYO-E_gQA2_BhYlcwcpUrWFrcV0gI8GRQ9gjlNVg/edit?usp=sharing).
