### ISSUE TITLE
Add 13 New Assessment Options in FishPath 

### ISSUE THREAD

**Issue by serenalomonico** [shcaba/FishPath-updates#42]
This Excel sheet contains 13 new Assessment Options to add into FishPath. Need to link each method with appropriate questions/caveats.

[New assessment methods to include in FishPath.xlsx](https://github.com/shcaba/FishPath-updates/files/1989737/New.assessment.methods.to.include.in.FishPath.xlsx)

**Comment by serenalomonico** [comment]
Also consider adding Extended Stock Synthesis (XSSS) and extended DB-SRA (XDB-SRA); 
Age-structured production models, COM-SIR, SS-COM.

**Comment by serenalomonico** [comment]
Consider adding LBB (Froese et al. 2018)
https://academic.oup.com/icesjms/advance-article/doi/10.1093/icesjms/fsy078/5051296

**Comment by shcaba** [comment]
Brian will put the xls into a Google spreadsheet so we are all able to work on the same spreadsheet,
link to follow.

**Comment by bsnouffer** [comment]
Here's a spreadsheet with all the options to be added that I could find in here and the previous spreadsheet. If you decide to write one up, just add your name to the assigned to column so I know not to work on it as well. 

https://docs.google.com/spreadsheets/d/1y1DcDig0kZlnQUEXhaiQ6wKbk9I__2TPHrVMF_ZuVaU/edit?usp=sharing

**Comment by dtdougherty** [comment]
Brian- Is this complete and can be put into communications or complete?

**Comment by bsnouffer** [comment]
Thanks for the reminder on this. It's finished and the options have been inputted into FishPath. (See the google doc for the details about which options added and changes made.)
