### ISSUE TITLE
Add 15 Point Process Guidance 

### ISSUE THREAD

**Issue by serenalomonico** [shcaba/FishPath-updates#49]
Add a link, PDF, or other material to summarize the 15 point process for narrowing down results. Make this accessible in the results section. Requires team R&D and Chad.

**Comment by serenalomonico** [comment]
Related: Create a button or ability to “filter results” which brings you to a new page where the user can filter by chosen, drop-down filters. Ideally build a process that can do the 15 steps post-results, leading to interactive/dynamic narrowing-down of results. Potentially sort results by data needs, outputs, etc. with various toggles so users have different ways to interact with results. For example, sorting by Assessment type vs. Reference point data type (could have both displayed on the screen and sort by one or the other).

**Comment by serenalomonico** [comment]
Additional note: (add to 15-point plan) Deciding among FishPath options – users could weight preferences and some kind of MDS analysis could be undertaken to identify profiles of preferred options.

**Comment by serenalomonico** [comment]
Additional notes from Natalie regarding 15-Point Plan for narrowing options:
Per 15-step plan’s original #1, also, Policy and legislative requirements – what are you being advised/advocated/required to do? (QDAF workshop).
Per 15-step plan’s original #6, also, if multisector/multispecies fishery, consider augmenting a more quantitative assessment(s) for individual, key species, with empirical indicator-based assessments that embrace all of the species collectively. (QDAF workshop).

Perhaps have a big “what’s next button” that links to Natalie’s management framework and a template and links for FMPS. Show how all the puzzle pieces fit together. How will users take these targets and move forward. We could provide guidance on how to select the right management strategy. Or just emphasize how this tool can support the understanding and direction that users will already likely be wanting to take. 

Need some way of pointing users to more robust assessments (e.g. obviously DBSRA is going to be superior to “expert judgement”)

**Comment by dtdougherty** [comment]
I think this has been addressed by our new "results review" interface. Some edits still coming, but this has been largely resolved.
