### ISSUE TITLE
Ability to show which assessment options were "almost" identified as possible options

### ISSUE THREAD

**Issue by serenalomonico** [shcaba/FishPath-updates#51]
Comment: In Assessment results, we see which options made it and which did not. We don’t see which “almost” made it. As this is a “selling point” of FishPath, it would be good to have the capability to be able to see which options “almost made it” out of vector-matching exercise.

**Comment by bsnouffer** [comment]
This was added a while ago. Now criteria icons show count of how many criteria were met or failed.
