### ISSUE TITLE
Ability for admins to export information from the database

### ISSUE THREAD

**Issue by serenalomonico** [shcaba/FishPath-updates#63]
Including: Excel sheet of questionnnaire order (with question number, question, answers, description) when you begin the questionnaire in a certain section, Excel sheets of caveats, etc. 
Having a questionnaire "hard copy" in the specified order is especially important (for printing out or saving before workshops to take notes or in case internet doesn't work)

**Comment by serenalomonico** [comment]
Ideally, an Admin OR a User will have the ability to download a file of linked questions/answers/result options/caveats. For an admin, this is important for adding new questions and cross-checking these linkages, as well as easily explaining the logic to partners. 

It would be nice in the user interface and especially in Admin to see the guts in a grid/spreadsheet format to get a bigger picture of what is going on.  In the admin interface it would be very useful to be able to export the grid-like interface for each of the spreadsheets for validation and demonstration.  It would also be nice for us to have some access to the underlying database to be able to query ourselves for testing and other uses.“Map” of spreadsheet-style matrix and “you are here” would be handy

**Comment by bsnouffer** [comment]
Admin functionality for this was adding in mcclintock-lab/FishPath#55. Leaving open for now to discuss what should be made available to users.

**Comment by serenalomonico** [comment]
Add the ability to export "question description" in addition to other fields

**Comment by bsnouffer** [comment]
Closing as this was addressed as noted above. And "question description" has been added where needed. Any new requests should go into their own issue to track individually both for admins and users. There is already an open issue regarding making the question and answers list available to users in #98.
