### ISSUE TITLE
Change question 2144, "How much is data collection valued and prioritized...?", from a criteria question to a caveat question

### ISSUE THREAD

**Issue by serenalomonico** [shcaba/FishPath-updates#64]
2144: How much is data collection valued and prioritized by the governance agency that oversees the fishery of interest?

From Dawn: Another one that we noted during the MSC meeting was that for an example fishery, on-board observers were eliminated due to the answer to the question "How is data collection valued and prioritized by the governance agency for the fishery of interest?". We need to either adjust the limits for this criteria question, or switch this to a caveat like we did for the questions around monetary investment and research capacity. I think this may be the last remaining criteria question. I actually think that makes sense to have no criteria for monitoring or decision rules, unless they are real criteria. (e.g. do you have a research vessel, do you have enforcement staff).

**Comment by serenalomonico** [comment]
During HI workshop (Aug 7-9 2018), this was reworded from “How much is data collection valued and prioritized by the governance agency that oversees the fishery of interest?” to “How much is data collection valued and prioritized by the governance agency that oversees, or other trusted organizations that support, the fishery of interest?”

**Comment by dtdougherty** [comment]
This is issue is covered in issue #136
