### ISSUE TITLE
Add New Question: "Is this a live fishery?"

### ISSUE THREAD

**Issue by serenalomonico** [shcaba/FishPath-updates#65]
Add New Question. "Is this a live fishery?" If so, eliminates monitoring via biological sampling of length/weight/otoliths etc)

From Natalie (Bribane workshop)

**Comment by dtdougherty** [comment]
This would require caveats that warn against data collected that would require killing animal. Red caveats across on issues with killing/handling of these live marketed species.

**Comment by dtdougherty** [comment]
Caveats did not save. Review again.

**Comment by NatalieDowling** [comment]
I have revised the question and added many more caveats. Pending approval.

**Comment by dtdougherty** [comment]
The caveats look good, thank you Natalie.
