### ISSUE TITLE
Add New Question about habitat changes

### ISSUE THREAD

**Issue by serenalomonico** [shcaba/FishPath-updates#67]
Add question(s) about habitat changes and include related management measures (From Rich (RI workshop)):

Has habitat quality changed over time? Gets at changes in structured habitat or changes in thermal habitat that could affect abundance and distribution, particularly shifts in distribution that may move a species out of an area and no change in fishing practices are going to fix that.

Are non-fishing, anthropogenic factors impacting the species critical habitat? Could relate to destruction of coral, mangrove or salt marsh areas, coastal development, forestry practices causing high levels of run-off, untreated sewage flowing right into fish habitat or dams stopping fish from getting to their spawning locations.

Include a decision rule that 1) suggests engagement with other government agencies, industry, or land owners groups, or 2) that habitat restoration activities may be needed to increase the fish stock.

**Comment by bsnouffer** [comment]
Discussed this on a call with Jason and Natale. 

In general, these issues, while important, fall outside the scope of a harvest strategy and therefore the Tool. However, we have updated the caveats for no-take zones, implement spatial closure in response to assessment, and gear mgmt to include that these could also be used to protect previously altered or damaged habitat.
