### ISSUE TITLE
Add New Questions about diadromous fish

### ISSUE THREAD

**Issue by serenalomonico** [shcaba/FishPath-updates#69]

**Comment by bsnouffer** [comment]
In discussion with Natalie and Jason, we decided that this question is not needed. We think that the issues that are relevant to this type of species are already covered under other more general questions. If an issue relating to diadromous fish that isn't already covered comes up, we can revisit to see if this question is needed or if it is an issue common to other types of fish as well and a more general question is needed.

One issue discussed specific to diadromous fish is that they are well suited to the use of escapement thresholds. This option is being added to the Tool. However, we don't think that it is enough to warrant the question and so instead we will add in the description of the new option "Escapement Thresholds" that it works well for diadromous fish.
