### ISSUE TITLE
Add "how to answer questions" jpeg or graphic on questionnaire intro page

### ISSUE THREAD

**Issue by serenalomonico** [shcaba/FishPath-updates#71]
Screenshot of a question with labels that explain the sections or headings.

**Comment by bsnouffer** [comment]
The user guide containing this information in detail is now published online. Also we are working on other tutorial/how to materials. I don't think a screenshot (or something similar) needs to be included at the start of every questionnaire at this point. Closing for now. Can reopen if anyone feels its needed.
