### ISSUE TITLE
Fix questionnaire order of 2 pairs of questions

### ISSUE THREAD

**Issue by serenalomonico** [shcaba/FishPath-updates#72]
Reorder so that question ID 214 (Von Bert) comes before ID 166 (m/k);
Reorder so that question ID 485 (deployment) comes before ID 395 (fleet rep)

From Natalie (Assessment revisions).

**Comment by serenalomonico** [comment]
Check with Natalie on this order: 
https://fishpath.org/admin/questionOrder

**Comment by NatalieDowling** [comment]
First reordering done.
The second one was already done.
