### ISSUE TITLE
Add Static Caveat: CPUE standardization and SCA options

### ISSUE THREAD

**Issue by serenalomonico** [shcaba/FishPath-updates#78]
From Natalie (Assessment revisions). See Column AV.
Add a static caveat to CPUE standardization and SCA options…

**Comment by serenalomonico** [comment]
clarify which spreadsheet - col AV

**Comment by bsnouffer** [comment]
@NatalieDowling I know this is from a while ago, but do you remember if this was addressed? 

There are a number of static caveats relating to CPUE for SCA and other options. They are listed below with the static caveat followed by the options it is triggered for. Let me know if the following addressed what was in the spreadsheet or if there is a different issue needing static caveats written for it.

> Static caveat regarding the use of CPUE: Use CPUE with extreme caution, consult local experts to understand degree to which technology or catchability may have changed over time.

For options:  
- Data exploration via plotting and descriptive statistics
- Depletion analysis
- CUSUM Control Charts
- Traffic lights
- Hierachical decision trees
- Sequential trigger framework involving catch and/or effort, CPUE, size, sex ratio etc.
- Sustainability Assessment for Fishing Effects (SAFE)
- Production model
- Statistical catch-at-age (SCAA)

> Static caveat regarding the use of CPUE: Use CPUE with extreme caution, consult local experts to understand degree to which technology or catchability may have changed over time. Requires explanatory variables - e.g. oceanographic, vessel type, area, time of year, moon phase etc., capturing changes in how fishery has operated.

For the options:
- Single-indicator analysis using standardized CPUE
- Linear regression to recent time series of CPUE

> Static caveat regarding the use of CPUE: For this method, if CPUE is used as a biomass proxy, it is typically as a snapshot rather than a time series. However, CPUE should generally be used with extreme caution, consult local experts to understand degree to which technology or catchability may have changed over time.

For the option:
- Use of biomass surveys to inform spatial management


Also, either way, I think that all of these can lose the opening clause as redundant "Static caveat regarding the use of CPUE:"

**Comment by NatalieDowling** [comment]
I think it's been addressed. The spreadsheet to which the original issue referred cites a column that asks about selectivity. I think Jason then picked up that we needed to add static caveats around the use of CPUE. I also agree that we can lose the opening clause, as you suggest.

**Comment by bsnouffer** [comment]
Thanks Natalie. I updated FishPath to remove the opening clause for all the options listed. Closing.
