### ISSUE TITLE
Make each "useful link" stand out. Make link blue font; hyperlink; and put on its own line.

### ISSUE THREAD

**Issue by serenalomonico** [shcaba/FishPath-updates#81]
For question descriptions or option descriptions that have useful links to code, put each link on its own line until we can change the software functionality to have a new section (such as "Code") similar to the "References" or sections.

**Comment by serenalomonico** [comment]
Need to address issue #151 (links open in new tab)

**Comment by dtdougherty** [comment]
this can be done by admins, you can bold, change color, have on separate lines, etc.
