### ISSUE TITLE
Check LB-SPR method

### ISSUE THREAD

**Issue by serenalomonico** [shcaba/FishPath-updates#82]
1. LBSPR currently require a time series of length frequency data, this should be adjusted so that a time series is not needed. One year is sufficient
2. LBSPR currently requires a "2- in situ" or higher, we think that "1-borrowed" and higher is more accurate.

This comment was from Jono a while back and was marked as complete, but need to double check this one.

**Comment by dtdougherty** [comment]
Double-checked in FP, change was made previously
