### ISSUE TITLE
Data and Control Rule color

### ISSUE THREAD

**Issue by shcaba** [shcaba/FishPath-updates#84]

**Comment by shcaba** [comment]
Some options still go from black to red, with no green answers (e.g., Independent Surveys: By practitioners, performed irregularly criterion 1). Is this correct, or is this the same problem we encountered in the assessment section, which is now corrected?

**Comment by underbluewaters** [comment]
I think I saw this during the Kaupulehu workshop.


https://lh4.googleusercontent.com/6U8HZIPQlxr4Kmof5_8B5BNAL6qQMOcj5MD_rFb8bX7sEEhXOuVrc-yA-V9COD-AxR3lv160vxT17TO_ReE4dRbMESkvEVsid0Z9vTo-42Te4saqKN3xWJ0AWWyzHY9mviNg5dDe
