### ISSUE TITLE
In Assessment section, add measure of data quality, not only quantity. 

### ISSUE THREAD

**Issue by serenalomonico** [shcaba/FishPath-updates#91]
Consider providing a static caveat for certain methods about data quality. Consider using CV.

**Comment by serenalomonico** [comment]
May also use the "Notes" section in FishPath to capture details/elaborate on fishery specific data challenges. 

Related note: Do assessment options identify if there are quality issues with indices? (e.g. CPUE is poor quality for Spanish Mackerel, only 4-5 operators

Indices: not just quantity but quality. Need to better define “useable” data (?hybrid Malcolm and Jason’s presentations?) (e.g. catch-only methods: need catch to reflect abundance; no one-way trips; no zeros at start or end of time series. DCAC, DB-SRA: can overcome lack of targeting because they incorporate an assumed level of depletion). Add in data cautions? – eg. as static caveats?

**Comment by bsnouffer** [comment]
Updated wording to the answers for time series questions in #168 speaks to data quality. However, leaving this open to allow for the possibility of a more robust way of addressing this.

**Comment by bsnouffer** [comment]
While going through peer review feedback, the time series answers are again being updated to better encapsulate data quality issues. This is being tracked in #382.
 In terms of 'useable' data, as noted this should be covered in the descriptions and possibly static caveats. There has been a thorough review of all the descriptions and many of the options static caveats. Closing this issue now. If there are specific issues where data quality or 'useable' data can be better defined, then please open up a new issue with the specific details.
