### ISSUE TITLE
Create additional screen for starting a new fishery

### ISSUE THREAD

**Issue by dtdougherty** [shcaba/FishPath-updates#99]
Create an input screen that defines the fishery, before a questionnaire is started. It would have users define: species, area, gear, fleet, etc. This would help with 1. making this more formal and easy to walk through in a workshop and 2) would help to store this information for each fishery so that we could use it for things later (maps of all fisheries, analyses). 

For now, we could just have a list of check marks, later have fill in that would be stored in database.

**Comment by serenalomonico** [comment]
Consider an optional field that asks users to state where they got the link. This would help ensure the FishPath team carefully documents all people they share the link with and understand how it's shared.

**Comment by serenalomonico** [comment]
Also add the time frame: specify if answers will be what you can do now, or what you can do in 5 years.

Additional comments from Natalie's notes:
Provide instruction that users have to make an upfront decision about how they are going to assimilate their data, and how they use FishPath to confront their fishery, particularly given multiple fleets/sectors/gears/selectivities. Ideally, a whole-of-stock combined assessment approach across sectors/gears is recommended, using either combined or representative data from one sector, UNLESS the selectivities are incompatible. Generally, the monitoring and decision rule sections should be contemplated separately for each sector/gear/fleet, albeit with the acknowledgement that there will be significant overlap in the questionnaire responses (those that differ can be flagged within the FishPath software for easy reference).

**Comment by serenalomonico** [comment]
Consider adding: Some kind of ability to ID/state upfront what the current issues are? E.g. in Queensland net fishery, there are literally 100s of pages of input controls, whose sheer volume may undermine effective management.

**Comment by dtdougherty** [comment]
Based on MRAG report, ensure that the questions also help to categorize fisheries that is useful in the MSC process around categorizing the stock.  See "FishPath as an output of a pre-assessment" section of report. Have MRAG or MSC review the questions to ensure they satisfy MSC classifications.

**Comment by underbluewaters** [comment]
@serenalomonico Can you get me the final list of questions by Feb 2nd? Please include which questions are optional.

**Comment by underbluewaters** [comment]
Steps:

- [x] Create FisheryMetadataDialog
- [x] Validate entries
- [x] Add actions to handle modifying existing fisheries
- [x] Ensure data saves to db
- [x] Update Homepage, Results, Questionnaire, Status Modal, Report Export, and Admin interfaces to display this information rather than the old "fishery" attribute
- [x] Modify fishery creation workflow to use FisheryMetadataDialog

**Comment by underbluewaters** [comment]
Something frustrating I'm noticing from this change is that it's going to be hard to consistently display a good title for each response. Right now when we list responses we do so with the "fishery" attribute, but that's made redundant by all this information and I don't think it makes sense to have that field anymore when starting a new fishery. Right now I'm using commonName + geography to form the title for lists and results, with a fallback to the fishery attribute if it's an old and un-updated response. I've made a makeTitle() function that is reused throughout the interface, so it should be pretty easy to change how titles are generated in the future. Depending on how things shake out we might want to generate titles from the commonName + gear type or something else.

**Comment by dtdougherty** [comment]
Thanks, Chad. Maybe we can just use the current field to populate
commonName and then edit manually the first time anyone access that fishery
again. They should be prompted to fill out the input form before getting
back into the results.
